### ISSUE TITLE
XCode Crashing after rnpm unlink

### ISSUE THREAD

**Issue by evanmrose** [rnpm/rnpm#106]
I just unlinked react-native-camera then reinstalled and relinked and now Xcode crashes each time I try to open the project. 

Error:

`Process:               Xcode [48567]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.2 (9548)
Build Info:            IDEFrameworks-9548000000000000~7
App Item ID:           497799835
App External ID:       814662604
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [48567]
User ID:               597893436

Date/Time:             2016-03-10 13:55:54.186 -0500
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        768037FD-A1F2-F6D7-495B-F4D44A448135

Sleep/Wake UUID:       FFD66E59-2E18-4BDF-BC26-844522237BBD

Time Awake Since Boot: 1000000 seconds
Time Since Wake:       590 seconds

Crashed Thread:        0  Dispatch queue: IDEContainer - uniquing lock

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
ProductBuildVersion: 7C68
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-9523/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/DataModel/Containers/PBXContainerItemProxy.m:135
Details:  _containerPortal is NULL
Object:   <PBXContainerItemProxy: 0x7fc7b565c2e0>
Method:   -remoteContainer
Thread:   <NSThread: 0x7fc7b1e2ba00>{number = 1, name = main}
Hints:   None
Backtrace:
  0  0x00000001075031fa -[IDEAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in IDEKit)
  1  0x000000010608c761 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010608c978 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010fc31d6f -[PBXContainerItemProxy remoteContainer] (in DevToolsCore)
  4  0x000000010fc31e7a -[PBXContainerItemProxy remoteContainerItem] (in DevToolsCore)
  5  0x000000010fc34b8e -[PBXReferenceProxy sourceTree] (in DevToolsCore)
  6  0x000000010fb4f35f -[PBXReference addNotifications] (in DevToolsCore)
  7  0x000000010fb55b8d -[PBXReference awakeFromPListUnarchiver:] (in DevToolsCore)
  8  0x000000010fc35adf -[PBXReferenceProxy awakeFromPListUnarchiver:] (in DevToolsCore)
  9  0x00007fff965af376 -[NSArray makeObjectsPerformSelector:withObject:] (in CoreFoundation)
 10  0x000000010fb6636e -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
 11  0x000000010fb3031d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
 12  0x000000010fd6bcab -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
 13  0x0000000106e1a010 __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
 14  0x00007fff8d153c13 _dispatch_client_callout (in libdispatch.dylib)
 15  0x00007fff8d154e5e _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
 16  0x00000001060c9005 DVTDispatchBarrierSync (in DVTFoundation)
 17  0x0000000105e61627 -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
 18  0x0000000106e199e7 __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
 19  0x0000000105fe7de3 __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 20  0x000000010607cab9 -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 21  0x0000000105fe7cee -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 22  0x0000000106e19776 +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 23  0x0000000106a90dae +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
 24  0x0000000106a9b04b -[IDEWorkspace _configureWrappedWorkspaceWithError:] (in IDEFoundation)
 25  0x0000000106e19a45 __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
 26  0x0000000106e19791 +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 27  0x0000000106a906e0 +[IDEContainer retainedWrappedWorkspaceForContainerAtFilePath:fileDataType:error:] (in IDEFoundation)
 28  0x0000000107726e43 -[IDEDocumentController _openWrappingContainerDocument:displayDocument:completionHandler:] (in IDEKit)
 29  0x000000010772a31b -[IDEDocumentController _openProjectsPlaygroundsAndWorkspaces:display:openedDocuments:simpleFileDocumentLocations:completionHandler:] (in IDEKit)
 30  0x0000000107729a97 -[IDEDocumentController _openProjectsPlaygroundsAndWorkspaces:display:completionHandler:] (in IDEKit)
 31  0x000000010772aaf9 -[IDEDocumentController _openDocumentsForDocumentLocations:display:completionHandler:] (in IDEKit)
 32  0x000000010772b43d -[IDEDocumentController asyncOpenDocumentsWithContentsOfURLs:display:completionHandler:] (in IDEKit)
 33  0x00000001073e2e4f -[IDEApplicationController _openFiles:] (in IDEKit)
 34  0x00000001073e274c -[IDEApplicationController application:openFiles:] (in IDEKit)
 35  0x00007fff88c72788 -[NSApplication(NSAppleEventHandling) _openDocumentURLs:withCompletionHandler:] (in AppKit)
 36  0x00007fff88c71639 __69-[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:]_block_invoke (in AppKit)
 37  0x00007fff88df30f0 __95-[NSPersistentUIManager restoreAllPersistentStateRegisteringAsReadyWhenDone:completionHandler:]_block_invoke557 (in AppKit)
 38  0x00007fff88b49949 __97-[NSDocumentController(NSInternal) _autoreopenDocumentsIgnoringExpendable:withCompletionHandler:]_block_invoke_3 (in AppKit)
 39  0x00007fff88b49491 -[NSDocumentController(NSInternal) _autoreopenDocumentsIgnoringExpendable:withCompletionHandler:] (in AppKit)
 40  0x00007fff88df3034 -[NSPersistentUIRestorer finishedRestoringWindowsWithZOrder:completionHandler:] (in AppKit)
 41  0x00007fff88df1d6c -[NSPersistentUIRestorer restoreStateFromRecords:usingDelegate:completionHandler:] (in AppKit)
 42  0x00007fff88df14a1 -[NSPersistentUIManager restoreAllPersistentStateRegisteringAsReadyWhenDone:completionHandler:] (in AppKit)
 43  0x00007fff88b47c07 -[NSApplication _reopenWindowsAsNecessaryIncludingRestorableState:registeringAsReady:completionHandler:] (in AppKit)
 44  0x00007fff88c6f795 -[NSApplication(NSAppleEventHandling) _handleAEOpenDocumentsForURLs:] (in AppKit)
 45  0x00007fff88b47586 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] (in AppKit)
 46  0x00007fff94fbb818 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] (in Foundation)
 47  0x0000000107504186 -[NSAppleEventManager(DVTAssertionOverrides) swizzleDispatchRawAppleEvent:withRawReply:handlerRefCon:] (in IDEKit)
 48  0x00007fff94fbb689 _NSAppleEventManagerGenericHandler (in Foundation)
 49  0x00000001074f5e22 HandleOpenDocAE (in IDEKit)
 50  0x00007fff8c84e43c aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) (in AE)
 51  0x00007fff8c84e1b9 dispatchEventAndSendReply(AEDesc const*, AEDesc*) (in AE)
 52  0x00007fff8c84e0c3 aeProcessAppleEvent (in AE)
 53  0x00007fff908dec6e AEProcessAppleEvent (in HIToolbox)
 54  0x00007fff88b40da2 _DPSNextEvent (in AppKit)
 55  0x00007fff88b3fe58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in AppKit)
 56  0x00000001066690c2 -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in DVTKit)
 57  0x00007fff88b35af3 -[NSApplication run] (in AppKit)
 58  0x00007fff88ab2244 NSApplicationMain (in AppKit)
 59  0x00007fff9615b5c9 start (in libdyld.dylib)`

**Comment by grabbou** [comment]
Also git diff of changes to pbxproj would help a lot!

**Comment by alexkehayias** [comment]
I also had this problem `rnpm v5.6.0` where unlinking causes Xcode Version 7.2 (7C68) to crash and anytime the project is opened again in Xcode it crashes. Other projects continue to work.

**Comment by grabbou** [comment]
Please submit a git diff after unlinking so we can see what lines were broken that could cause Xcode to crash.

Or feel free to send `pbxproj` via email if it's rather sensitive.

**Comment by alexkehayias** [comment]
Here's the git diff after unlinking:

```
diff --git a/android/app/build.gradle b/android/app/build.gradle
index f882bb7..5f55003 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -120,7 +120,6 @@ android {
 }

 dependencies {
-    compile project(':react-native-camera')
     compile fileTree(dir: "libs", include: ["*.jar"])
     compile "com.android.support:appcompat-v7:23.0.1"
     compile "com.facebook.react:react-native:+"  // From node_modules
diff --git a/android/app/src/main/java/com/boople/MainActivity.java b/android/app/src/main/java/com/boople/MainActivity.java
index d988cb1..abed869 100644
--- a/android/app/src/main/java/com/boople/MainActivity.java
+++ b/android/app/src/main/java/com/boople/MainActivity.java
@@ -1,7 +1,6 @@
 package com.boople;

 import com.facebook.react.ReactActivity;
-import com.lwansbrough.RCTCamera.RCTCameraPackage;
 import com.facebook.react.ReactPackage;
 import com.facebook.react.shell.MainReactPackage;

@@ -35,8 +34,7 @@ public class MainActivity extends ReactActivity {
     @Override
     protected List<ReactPackage> getPackages() {
         return Arrays.<ReactPackage>asList(
-            new MainReactPackage(),
-        new RCTCameraPackage()
+            new MainReactPackage()
         );
     }
 }
diff --git a/android/settings.gradle b/android/settings.gradle
index f4c199d..f128b64 100644
--- a/android/settings.gradle
+++ b/android/settings.gradle
@@ -1,5 +1,3 @@
 rootProject.name = 'Boople'

 include ':app'
-include ':react-native-camera'
-project(':react-native-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-camera/android')
diff --git a/ios/Boople.xcodeproj/project.pbxproj b/ios/Boople.xcodeproj/project.pbxproj
index 47f4c90..315f0fc 100644
--- a/ios/Boople.xcodeproj/project.pbxproj
+++ b/ios/Boople.xcodeproj/project.pbxproj
@@ -5,7 +5,6 @@
        };
        objectVersion = 46;
        objects = {
-
 /* Begin PBXBuildFile section */
                00C302E51ABCBA2D00DB3ED1 /* libRCTActionSheet.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 00C302AC1ABCB8CE00DB3ED1 /* libRCTActionSheet.a */; };
                00C302E71ABCBA2D00DB3ED1 /* libRCTGeolocation.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 00C302BA1ABCB90400DB3ED1 /* libRCTGeolocation.a */; };
@@ -21,7 +20,6 @@
                13B07FC11A68108700A75B9A /* main.m in Sources */ = {isa = PBXBuildFile; fileRef = 13B07FB71A68108700A75B9A /* main.m */; };
                146834051AC3E58100842450 /* libReact.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 146834041AC3E56700842450 /* libReact.a */; };
                832341BD1AAA6AB300B99B32 /* libRCTText.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 832341B51AAA6A8300B99B32 /* libRCTText.a */; };
-               DB4FF47EDBAE43FAB54AA746 /* libRCTCamera.a in Frameworks */ = {isa = PBXBuildFile; fileRef = CE387C2F3C90408D9781245D /* libRCTCamera.a */; };
 /* End PBXBuildFile section */

 /* Begin PBXContainerItemProxy section */
@@ -123,10 +121,8 @@
                13B07FB61A68108700A75B9A /* Info.plist */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.plist.xml; name = Info.plist; path = Boople/Info.plist; sourceTree = "<group>"; };
                13B07FB71A68108700A75B9A /* main.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; name = main.m; path = Boople/main.m; sourceTree = "<group>"; };
                146833FF1AC3E56700842450 /* React.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = React.xcodeproj; path = "../node_modules/react-native/React/React.xcodeproj"; sourceTree = "<group>"; };
-               659E504B4F0B4979A1FEC5E2 /* RCTCamera.xcodeproj */ = {isa = PBXFileReference; explicitFileType = undefined; fileEncoding = 0; includeInIndex = 0; lastKnownFileType = "wrapper.pb-project"; name = RCTCamera.xcodeproj; path = "../node_modules/react-native-camera/ios/RCTCamera.xcodeproj"; sourceTree = "<group>"; };
                78C398B01ACF4ADC00677621 /* RCTLinking.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = RCTLinking.xcodeproj; path = "../node_modules/react-native/Libraries/LinkingIOS/RCTLinking.xcodeproj"; sourceTree = "<group>"; };
                832341B01AAA6A8300B99B32 /* RCTText.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = RCTText.xcodeproj; path = "../node_modules/react-native/Libraries/Text/RCTText.xcodeproj"; sourceTree = "<group>"; };
-               CE387C2F3C90408D9781245D /* libRCTCamera.a */ = {isa = PBXFileReference; explicitFileType = undefined; fileEncoding = 0; includeInIndex = 0; lastKnownFileType = archive.ar; path = libRCTCamera.a; sourceTree = "<group>"; };
 /* End PBXFileReference section */

 /* Begin PBXFrameworksBuildPhase section */
@@ -144,7 +140,6 @@
                                832341BD1AAA6AB300B99B32 /* libRCTText.a in Frameworks */,
                                00C302EA1ABCBA2D00DB3ED1 /* libRCTVibration.a in Frameworks */,
                                139FDEF61B0652A700C62182 /* libRCTWebSocket.a in Frameworks */,
-                               DB4FF47EDBAE43FAB54AA746 /* libRCTCamera.a in Frameworks */,
                        );
                        runOnlyForDeploymentPostprocessing = 0;
                };
@@ -267,7 +262,6 @@
                                832341B01AAA6A8300B99B32 /* RCTText.xcodeproj */,
                                00C302DF1ABCB9EE00DB3ED1 /* RCTVibration.xcodeproj */,
                                139FDEE61B06529A00C62182 /* RCTWebSocket.xcodeproj */,
-                               659E504B4F0B4979A1FEC5E2 /* RCTCamera.xcodeproj */,
                        );
                        name = Libraries;
                        sourceTree = "<group>";
@@ -551,7 +545,6 @@
                                        "$(inherited)",
                                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
                                        "$(SRCROOT)/../node_modules/react-native/React/**",
-                                       "$(SRCROOT)/../node_modules/react-native-camera/ios",
                                );
                                INFOPLIST_FILE = Boople/Info.plist;
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
@@ -569,7 +562,6 @@
                                        "$(inherited)",
                                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
                                        "$(SRCROOT)/../node_modules/react-native/React/**",
-                                       "$(SRCROOT)/../node_modules/react-native-camera/ios",
                                );
                                INFOPLIST_FILE = Boople/Info.plist;
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
@@ -616,7 +608,6 @@
                                        "$(inherited)",
                                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
                                        "$(SRCROOT)/../node_modules/react-native/React/**",
-                                       "$(SRCROOT)/../node_modules/react-native-camera/ios",
                                );
                                IPHONEOS_DEPLOYMENT_TARGET = 7.0;
                                MTL_ENABLE_DEBUG_INFO = YES;
@@ -657,7 +648,6 @@
                                        "$(inherited)",
                                        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
                                        "$(SRCROOT)/../node_modules/react-native/React/**",
-                                       "$(SRCROOT)/../node_modules/react-native-camera/ios",
                                );
                                IPHONEOS_DEPLOYMENT_TARGET = 7.0;
                                MTL_ENABLE_DEBUG_INFO = NO;

```

**Comment by grabbou** [comment]
Closing in favour of #134. This is fixed and getting shipped!
