### ISSUE TITLE
React Native 0.21.0 :  running "rnpm link" outputs nothing in console

### ISSUE THREAD

**Issue by VansonLeung** [rnpm/rnpm#107]
React Native 0.21.0 :  running "rnpm link" outputs nothing in console
and it seems not linking anything of iOS and Android dependencies of the node modules into project.

I tested "npm install react-native-spinkit --save" and then "rnpm link"

And then after 1 second the command is complete, but no logs come out and the dependencies are not yet linked.

**Comment by Kureev** [comment]
Try to update your rnpm to version 1.5.1, that should solve your issue.
Let me know if it doesn't work for you, I'll re-open this issue.

**Comment by VansonLeung** [comment]
I just updated to rnpm@1.5.1

And then I created new project by "react-native init rnpm_test_3"

And my package.json is being spawned as below:

{
  "name": "rnpm_test_3",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "^0.21.0",
    "react-native-spinkit": "0.0.7"
  }
}


When I try "rnpm link" it still outputs nothing in console and then after 1 second the command is complete without doing anything.

**Comment by Kureev** [comment]
I can't reproduce what you're saying.
![image](https://cloud.githubusercontent.com/assets/2273613/13751751/e7f9b5fe-ea0b-11e5-905a-aea93d6a3dc5.png)

Which platform do you use?

**Comment by VansonLeung** [comment]
Ok, I found that the bug only happens when I use react-native-spinkit library.
It seems it is this library which does not support rnpm.
I need to investigate that library instead. Closing

**Comment by grabbou** [comment]
Please cc author here or in his repo so we can help!
