### ISSUE TITLE
iOS - findProjects would Skip all projects having names : *example* , *test*

### ISSUE THREAD

**Issue by VansonLeung** [rnpm/rnpm#109]
I just found out the reason for #107

In: findProjects.js

`const GLOB_EXCLUDE_PATTERN = ['node_modules/**', '**/*@(E|e)xample*/**', '**/*@(T|t)est*/**', 'Pods/**'];
`

And I just named my project name as rnpm_test_1

then when I run "rnpm link", it just skipped "rnpm_test_4.xcodeproj" and links nothing for iOS at all.

**Comment by Kureev** [comment]
strange, `**/*@(T|t)est*/**` shouldn't ignore any end-files, only folders.
Do I miss something, @grabbou?

**Comment by grabbou** [comment]
Yes, that's how it works, although it's unlikely we will update that glob. 

Can you set path to project manually in package.json as a custom rnpm config? That way, you will skip findProject() entirely.

**Comment by grabbou** [comment]
(@Kureev it's likely outer folder has the same name if rn generator was used)
