### ISSUE TITLE
`rnpm link` does not properly link library

### ISSUE THREAD

**Issue by chandlervdw** [rnpm/rnpm#112]
I even tried `rnpm link react-native-blur` and I get 
`rnpm-link info Linking react-native-blur ios dependency`
`rnpm-link info iOS module react-native-blur has been successfully linked`

I still get these errors: 
`ExceptionsManager.js:76Warning: Native component for "BlurView" does not exist`
`ExceptionsManager.js:76 Warning: Native component for "VibrancyView" does not exist`

**Comment by grabbou** [comment]
Thanks for the report, I'll take a look at that today

**Comment by grabbou** [comment]
@Kureev I can see libRNBlur.a being added properly with `rnpm` - can you help me with this one? (it's your :ship:)

**Comment by chandlervdw** [comment]
Not at my machine at the moment but it’s possible that I forgot to recompile the project. I will update as soon as I can. 

--

Chandler

On Sat, Mar 19, 2016 at 5:31 PM Mike Grabowski

<
mailto:Mike Grabowski <notifications@github.com>
> wrote:

https://github.com/Kureev
I can see libRNBlur.a being added properly with

rnpm

- can you help me with this one? (it's your

)

**Comment by grabbou** [comment]
ok,thanks

**Comment by chandlervdw** [comment]
@grabbou @Kureev recompiling the project did the trick. Sorry for the false alarm.
