### ISSUE TITLE
rnpm link on Windows adds invalid path format in settings.gradle

### ISSUE THREAD

**Issue by nikolaia** [rnpm/rnpm#113]
Using `rnpm link project-name` on Windows gives you a `settings.gradle` file that is invalid:

```
rootProject.name = 'example'

include ':app'
include ':project-name'
project(':project-name').projectDir = new File(rootProject.projectDir, '..\node_modules\project-name\android')
``` 

Changing from the escapecharacters `\` to `/` makes it work.

**Comment by Kureev** [comment]
https://github.com/rnpm/rnpm-plugin-link/pull/36 supposed to solve this issue. We're waiting for an author feedback. If you want to help us ship it faster, you can compose a new PR taking into account our hints in  the current one.

**Comment by grabbou** [comment]
Thanks, that's now live as 1.6.2 (link). You can either reinstall rnpm globally to get new version or just cd to rnpm directory and npm install rnpm-plugin-link!

**Comment by nikolaia** [comment]
Reinstalled. Works great. Thanks :+1:
