### ISSUE TITLE
rnpm does not correctly link react-native-system-notification

### ISSUE THREAD

**Issue by cancan101** [rnpm/rnpm#115]
https://github.com/Neson/react-native-system-notification does not correctly link for Android.

Rather than getting:
```java
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new NotificationPackage(this)                  // <- Add this line
        );
    }
```

I got (no `this`):
```java
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new NotificationPackage()
        );
    }
```

**Comment by Kureev** [comment]
That's a known thingy. We're currently working on this :heart:

**Comment by Kureev** [comment]
Btw, before we roll out a better solution, I suggest you to contact a library author to add a special "rnpm" settings to the `package.json`:

```json
"rnpm": {
  "android": {
    "packageInstance": "new NotificationPackage(this)"
  }
}
```

**Comment by Kureev** [comment]
But it also seems that this library requires some extra things that rnpm doesn't support yet. I'll do my best to make it possible to link these kind of libraries using our tool :wink:

**Comment by grabbou** [comment]
For now I think we should close this one as it's not really an issue. Let's track progress of that work in a separate place.

**Comment by Kureev** [comment]
true, the real issue is deeper than passing "this" to the instance.
