### ISSUE TITLE
rnpm link for `react-native-push-notification` does not do anything

### ISSUE THREAD

**Issue by cancan101** [rnpm/rnpm#116]
Running rnpm link after `npm i --save react-native-push-notification` (https://github.com/zo0r/react-native-push-notification) did not make any changes for Android.

**Comment by grabbou** [comment]
The author uses non-standard name for its android folder (it's `RNPushNotificationAndroid` whereas most of the community follows convention of using `android` folder as a name). Please contact the developer if he could rename it to `android`)

**Comment by grabbou** [comment]
@cancan101 that was fast!
