### ISSUE TITLE
rnpm link TypeError

### ISSUE THREAD

**Issue by cmcewen** [rnpm/rnpm#117]
I'm getting a bunch of successful package link messages, and then this:

```
/Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/mapHeaderSearchPaths.js:25
        .filter(path => path.indexOf('react-native/React/**'))
         ^

TypeError: (buildSettings.HEADER_SEARCH_PATHS || []).filter is not a function
    at /Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/mapHeaderSearchPaths.js:25:10
    at Array.forEach (native)
    at headerSearchPathIter (/Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/mapHeaderSearchPaths.js:22:6)
    at addToHeaderSearchPaths (/Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/addToHeaderSearchPaths.js:4:3)
    at registerNativeModuleIOS (/Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/registerNativeModule.js:56:5)
    at /Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:44:24
    at fn (/Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
    at /Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
    at /Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
    at /Users/cmcewen/.nvm/versions/node/v5.7.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
```
rnpm is at `1.5.2`, react-native is `0.22`

**Comment by grabbou** [comment]
Hey,

would you mind console.logging what is type of buildSettings.HEADER_SEARCH_PATHS as well as its value in that failing method? Looks like it's not an array (which is fine and is probably an edge-case).

**Comment by cmcewen** [comment]
`HEADER_SEARCH_PATHS: '"$(inherited)"'`
typeof gives me a `string`

**Comment by grabbou** [comment]
Ok, thank you! I'll try to reproduce this and come up with a reason for this happening.

**Comment by cmcewen** [comment]
Did some more digging - our project is configured to have multiple build targets, so the header search paths are defined at the project level not in targets. This should take care of that case: https://github.com/rnpm/rnpm-plugin-link/pull/48/files

**Comment by grabbou** [comment]
Hm, true. Thanks for checking that out! However - the purpose of that was to add new headers to the search path (from 3rd party libs) so you will get build issues if we don't add it. Maybe we should check for header search paths at project_level as well?
