### ISSUE TITLE
Provide package.json option for linking iOS shared libraries

### ISSUE THREAD

**Issue by appden** [rnpm/rnpm#122]
Since React Native (and therefore `rnpm`) expects native modules to be linked in as static libraries, it's up to the application to link to the shared libraries that the static library might need (frameworks seem to be automatically handled by the module auto-linking feature). As a native module author, you can provide additional setup instructions or try to automate it yourself, like we do in our `postlink` script [here](https://github.com/realm/realm-js/blob/master/scripts/rnpm-postlink.js).

I think it would great if `rnpm` automated this step by allowing a native module to specify its shared library dependencies in its `package.json`, like this:

```json
"rnpm": {
  "ios": {
    "sharedLibraries": ["libc++", "libxml2", "libz"]
  }
}
```

Also, during the `unlink` stage, it would be able to know which shared libraries are still depended upon versus which ones it can safely remove.

**Comment by grabbou** [comment]
Yeah that's quite cool! Would love to see that as a part of link itself.

After looking at your code, looks like you would greatly profit from the feature issue I have been delaying all the time - to extract out `link/src/ios` functions to a separate consumable repo (e.g we already have a auto-Libraries group creation, so we could add that as well).

I think we could hook here https://github.com/rnpm/rnpm-plugin-link/blob/master/src/ios/registerNativeModule.js#L48 with a function `addSharedLibraries(project, config.sharedLibraries)` and all the logic you currently have would go in there.

**Comment by grabbou** [comment]
Here's the simple PR I've made for you if you would be interesting in implementing that feature! https://github.com/rnpm/rnpm-plugin-link/pull/50 Feel free to submit PR to that PR :)

(Also don't forget to clone rnpm itself and switch to the branch with the same name to get an array of sharedLibraries from getDependencyConfig)

**Comment by grabbou** [comment]
@appden I am so excited to get this done finally! We've been scheduling this feature all over again and finally sounds like someone finally did present a clean starter for that! Thanks!

**Comment by lostintangent** [comment]
Any updates on this feature? This would be immensely useful for us (the CodePush team) as well!

**Comment by grabbou** [comment]
I am mainly waiting for @appden feedback on that :) If he does not have enough time, I'll probably try bringing it over the weekend!

Would you guys mind sharing your potential use-case? Just so we can test some of them

**Comment by lostintangent** [comment]
The CodePush plugin depends on `libz` being linked to the app project. Right now, our entire iOS steps for installation are RNPM-based (and awesome!), but we still have to expect the user to manually link `libz` after running `rnpm link`. We could definitely do the `postlink` script to do this linking ourselves, but I would much prefer this proposal :)

**Comment by lostintangent** [comment]
FYI, since it's completely impact less to our users, I just went ahead and added the `ios/sharedLibraries` config to our `package.json` file so that when this feature is added, it will just light up. If you want, you could actually use `rnpm install react-native-code-push` as a test case for this feature, since the Xcode project wouldn't compile if you didn't manually link `libz` or this RNPM feature didn't exist.

**Comment by plrthink** [comment]
I have the same use case. I am making [react-native-zip-archive](https://github.com/plrthink/react-native-zip-archive) package which also needs `libz` to be linked after user running `rnpm link`.

This feature is definitely useful for this module.

**Comment by grabbou** [comment]
cc: @alloy

**Comment by gnestor** [comment]
@appden How were you able to link frameworks using rnpm? I have tried linking the frameworks in my library and then rnpm linking the library to my project, but I still have to manually link the framework to my project. 

@grabbou Assuming this upcoming feature supports linking frameworks, should package.json theoretically look like:

```json
"rnpm": {
  "ios": {
    "sharedLibraries": ["AudioToolkit.framework", "Foundation.framework"]
  }
}
```

**Comment by appden** [comment]
@gnestor we have a `postlink` script that looks like [this](https://github.com/realm/realm-js/blob/master/scripts/rnpm-postlink.js). I'm curious why you found you needed to manually link frameworks? There is an option in Xcode that is enabled by default called `Link Frameworks Automatically` that should automatically do this for you. Here's a description of that feature:

> Auto Linking is enabled for frameworks imported by code modules. When a source file includes a header from a framework that supports modules, the compiler generates extra information in the object file to automatically link in that framework. The result is that, in most cases, you will not need to specify a separate list of the frameworks to link with your target when you use a framework API that supports modules.

**Comment by gnestor** [comment]
@appden Good find! This feature seems to be enabled by default so that solves my problem!
