### ISSUE TITLE
rnpm link fails,no error message

### ISSUE THREAD

**Issue by tttpeng** [rnpm/rnpm#127]
$ rnpm link
rnpm-link info Linking react-native-vector-icons android dependency
rnpm-link info Linking realm android dependency
$
Nothing happens after that message. I tried unlinking and it says its not linked yet.

$ rnpm unlink realm
rnpm-link info Unlinking realm android dependency
rnpm-link info Android module realm is not linked yet
rnpm-link info Unlinking realm ios dependency
rnpm-link info iOS module realm is not linked yet

node 5.6.0
npm 3.8.3
rnpm 1.5.4
react-native 0.22.2

**Comment by Kureev** [comment]
I'm working on this issue right now. I'll let you know when it'll be fixed. Sorry for this.

**Comment by Kureev** [comment]
Issue is found. Going to roll out a hotfix in a 10 mins.

**Comment by Kureev** [comment]
Updating `rnpm-plugin-link` to version 1.6.7 should fix the issue.

**Comment by tttpeng** [comment]
thanks!!!

**Comment by grabbou** [comment]
SLA :100:
