### ISSUE TITLE
Crashes attempting to parse Pods/Pods.xcodeproj/project.pbxproj

### ISSUE THREAD

**Issue by ScandyMark** [rnpm/rnpm#129]
while doing 'rnpm link NODE_MODULE_NAME' program crashes attempting to parse ios/Pods/Pods.xcodeproj/project.pbxproj   an xml file written by pod install

src/config/ios/findProject.js  findProject  gets a projects array
[ 'ios/Pods/Pods.xcodeproj',
  'ios/Scandy.xcodeproj',
  'ios/ScandyNative.xcodeproj' ]
[ 'ios/SCDOne.xcodeproj' ]
and goes with projects[0]

if all my debugging didn't mess things up, then the parser throws an syntax error uncaught when
executing 
      const didLinkIOS = registerDependencyIOS(dependency.config.ios, project.ios

**Comment by grabbou** [comment]
Hey, 

Check out similar issue we had -> https://github.com/rnpm/rnpm/issues/111#issuecomment-202561638

BTW - shouldnt it select ScandyNative for instance?

**Comment by ScandyMark** [comment]
some more info
$ pod --version
0.39.0

Main project is ios/Scandy.xcodeproj.  Wish I could tell more about the logic of the structure, but is something I am walking into, not something I set up on day 1.

**Comment by grabbou** [comment]
Fixed in #128, thank you!

**Comment by ScandyMark** [comment]
Verifying that this no longer crashes on me.  Thanks.

Having other trouble, will generate new issue in the unlikely event that I'm not the source of the other trouble.

**Comment by grabbou** [comment]
Haha, ok! In case it's our fault - feel free to post an issue, some of the things are still hypothetical solutions we haven't covered fully yet :)
