### ISSUE TITLE
rnpm-link ERR! ERRPLIST Could not locate Info.plist. Check if your project has 'INFOPLIST_FILE' set properly

### ISSUE THREAD

**Issue by cancan101** [rnpm/rnpm#130]
I am getting:
```
rnpm-link ERR! ERRPLIST Could not locate Info.plist. Check if your project has 'INFOPLIST_FILE' set properly
```
even though I see: `INFOPLIST_FILE = myApp/Info.plist;`

**Comment by grabbou** [comment]
Hm, that might be related to how the project is structured. Have you created it with `react-native init` or is it a custom set-up? Is linking working normally for all other dependencies? (I assume the only issue is when linking assets)

**Comment by cancan101** [comment]
I created initially with `react-native init`. I am using cocoapods so there is a workspace.

**Comment by grabbou** [comment]
Does linking of other libraries work properly?

**Comment by cancan101** [comment]
I think so:
>
> ...
> rnpm-link info Linking react-native-zip-archive android dependency
> rnpm-link info Android module react-native-zip-archive is already linked
> rnpm-link info Linking react-native-zip-archive ios dependency
> rnpm-link info iOS module react-native-zip-archive is already linked
> rnpm-link info Linking assets to ios project
> rnpm-link ERR! ERRPLIST Could not locate Info.plist. Check if your
> project has 'INFOPLIST_FILE' set properly
> rnpm-link info Linking assets to android project
> rnpm-link info Assets has been successfully linked to your project

**Comment by cancan101** [comment]
> ...
> rnpm-link info Linking react-native-zip-archive android dependency
> rnpm-link info Android module react-native-zip-archive is already linked
> rnpm-link info Linking react-native-zip-archive ios dependency
> rnpm-link info iOS module react-native-zip-archive is already linked
> rnpm-link info Linking assets to ios project
> rnpm-link ERR! ERRPLIST Could not locate Info.plist. Check if your
> project has 'INFOPLIST_FILE' set properly
> rnpm-link info Linking assets to android project
> rnpm-link info Assets has been successfully linked to your project

**Comment by grabbou** [comment]
If you are using CocoaPods, please check if latest 1.5.5 release fixes it for you :)

**Comment by grabbou** [comment]
I think this is already fixed - if not - please reopen and we will check what's going on here :)

**Comment by kvieira90** [comment]
Having this same issue after modifying the Info.plist file. I've looked at my file side by side with a brand new project and they're identical so not sure why a edit would cause RNPM link to fail

**Comment by grabbou** [comment]
Are you sure you are getting the same error message? Do you use CocoaPods?

**Comment by kvieira90** [comment]
I was, I ended up scrapping the entire repo and starting over without touching the info.plist from my editor. All set now but was a weird issue

**Comment by SudoPlz** [comment]
Same error!

**Comment by Kureev** [comment]
Sounds like you're copying .xcodeproj without appropriate folder near it (`Test.xcodeproj` should be copied with `Test` folder near it, otherwise link to the plist file is broken).

I feel like we have to re-open it again, since the issue wasn't fixed yet.

**Comment by SudoPlz** [comment]
@Kureev would you be kind enough to elaborate more on this? I haven't copied my main react native project anywhere. I might have copied sub projects but then again I thought INFOPLIST_FILE only refers to our main project right?

**Comment by Kureev** [comment]
I'd like to help, but I need to see a project to say something specific. Is it an OSS?

**Comment by SudoPlz** [comment]
I'm just trying to include the https://github.com/SudoPlz/react-native-bugsnag to a react-native xcode project, using Carthage. After doing that `rnpm link assets` no longer works. I get this error.

**Comment by SudoPlz** [comment]
Ok error was gone with a `git clean -fd`. Apparently I had many old sh1t on my Xcode project because of Cocoapods (which I have now removed).

**Comment by SudoPlz** [comment]
Ok UPDATE: 
Deleting my `Carthage/Checkouts/` directory from within the iOS project makes this error go away..! It has definitely something to do with Carthage and/or the way the installed project is structured (in my case I'm using the carthage project found in `github "bugsnag/bugsnag-cocoa"`.

I hope this helps someone.

**Comment by Kureev** [comment]
I think you can deliver even better DX to your users:
1. Use [manual bugsnag installation guide](http://docs.bugsnag.com/platforms/ios-objc/#manual-installation) to build their SDK (without any third-party tool like cocoapods or carthage) on your machine.
2. Once you have a working SDK on your machine, you can use it as a dependency of your module. We have no release notes for this feature, but I had exactly the same case in [react-native-uber-rides](https://github.com/Kureev/react-native-uber-rides).
3. Take a look on this part of [package.json config](https://github.com/Kureev/react-native-uber-rides/blob/master/package.json#L21-L28)

**Comment by SudoPlz** [comment]
Sounds good @Kureev, would you mind joining us in https://gitter.im/SudoPlz/react-native-bugsnag, it seems you've got lots of good suggestions to offer. Its an open source project if you can make a pull request I'll be more than happy to merge it..!

**Comment by Kureev** [comment]
I'll try to take a look when I have a free time.

I know, it can be really complicated to get it done right, especially if you never did it before.

I'm also about to close this issue because it loses a point.

**Comment by rc452860** [comment]
I‘m also encounter this problem:
rnpm-link info Linking react-native-admob android dependency 
rnpm-link info Android module react-native-admob has been successfully linked 
rnpm-link info Linking react-native-admob ios dependency 
rnpm-link info iOS module react-native-admob has been successfully linked 
rnpm-link info Android module react-native-material-kit is already linked 
rnpm-link info iOS module react-native-material-kit is already linked 
rnpm-link info Linking react-native-sqlite-storage ios dependency 
rnpm-link info iOS module react-native-sqlite-storage has been successfully linked 
rnpm-link info Android module react-native-update is already linked 
rnpm-link info iOS module react-native-update is already linked 
rnpm-link info Android module react-native-vector-icons is already linked 
rnpm-link info Linking react-native-vector-icons ios dependency 
rnpm-link info iOS module react-native-vector-icons has been successfully linked 
rnpm-link info Linking assets to ios project 
rnpm-link ERR! ERRPLIST Could not locate Info.plist. Check if your project has 'INFOPLIST_FILE' set properly
rnpm-link info Linking assets to android project 
rnpm-link info Assets has been successfully linked to your project

**Comment by SudoPlz** [comment]
@rc452860 If you are using `Carthage` make sure you delete the `Checkout` folder and then `rnpm link` will work again.
