### ISSUE TITLE
rnpm link with pods may not work well

### ISSUE THREAD

**Issue by L-Jovi** [rnpm/rnpm#131]
I use latest release rnpm, and it works well.

but when I add pods which manage dependences of my project,  I find that all link from rnpm move to __Pods.xcodeproj__ project, like image below.

![screen shot 2016-04-05 at 9 47 19 am](https://cloud.githubusercontent.com/assets/7262199/14269113/2e2c35e2-fb14-11e5-82a6-59729f1d9437.png)

actually I couldn't use one of above two libs in my project even pods already own them, now I have to add `*.a` lib manually to my project.

how should I fix it :(

thanks for your time.

regards.

**Comment by grabbou** [comment]
Fixed in #128, getting released today!

**Comment by L-Jovi** [comment]
cool !
