### ISSUE TITLE
Don't need to link projects in Sample/Example(s)

### ISSUE THREAD

**Issue by cpunion** [rnpm/rnpm#135]
Many react native libraries has a Sample/Example(s) folder and has iOS/android project in it(e.g. https://github.com/race604/react-native-viewpager), we don't need to link that projects.

Before https://github.com/rnpm/rnpm/commit/3b03abf39ad477554a5aa22f2f30146b1357d77a#diff-2683058bcad92e1272ec697fed36ba90R22 rnpm ignores Test/Example(s) folders, why remove that? I suggest add Test/Example/Sample to ignore lists.

**Comment by Kureev** [comment]
We still have this check here: https://github.com/rnpm/rnpm/commit/3b03abf39ad477554a5aa22f2f30146b1357d77a#diff-2683058bcad92e1272ec697fed36ba90R40

**Comment by Kureev** [comment]
Do you have any issues after that, @cpunion?

**Comment by cpunion** [comment]
@Kureev Thanks. Could you please add `sample` into it?

**Comment by Kureev** [comment]
Sure. But I'm a bit busy now, can't give you an ETA for this. 
Probably, you can find some time to compose a PR? I would be glad to merge it 👍

**Comment by cpunion** [comment]
@Kureev I will try.

**Comment by grabbou** [comment]
Merged, thanks!
