### ISSUE TITLE
rnpm link react-native-vector-icons is hanging

### ISSUE THREAD

**Issue by cancan101** [rnpm/rnpm#138]
Whenever I run `rnpm link react-native-vector-icons` , the process hangs until i ctrl-c out. There is nothing printed.

I have `react-native-vector-icons@1.3.4`.

**Comment by cancan101** [comment]
This seems to be an issue with rnpm 1.6.0. 1.5.0 works fine.

**Comment by cpunion** [comment]
Same. +1

**Comment by grabbou** [comment]
Fixed in 1.6.1.
