### ISSUE TITLE
Support multiple `xcodeproj` in a package (e.g. fbsdk)

### ISSUE THREAD

**Issue by kennetpostigo** [rnpm/rnpm#144]
Does rnpm work with this:
[react-native-fbsdk](https://github.com/facebook/react-native-fbsdk)

It's facebooks package for their sdk

**Comment by grabbou** [comment]
RNPM currently does not support multiple projects located in a single repository (that's the case I guess). Support to be considered.

**Comment by kennetpostigo** [comment]
Thank you for getting back so quickly. Do you by any chance know if there are any facebook sdk's that `rnpm` can automatically link?

**Comment by grabbou** [comment]
I am not aware of any others (I mainly use login) - if you have any others you know - feel free to list them here so we can use them as our test cases

**Comment by grabbou** [comment]
(Most likely we just link the first project we have found which is `fbsdk-core`. Can be solved with an array to be accepted, will try to tackle this later this week as there's also @knowbody affected and others)

**Comment by knowbody** [comment]
awesome, thanks!

**Comment by dzhuowen** [comment]
It'll be great if rnpm can support react-native-fbsdk! We stick with the package pattern of [native facebook sdk](https://github.com/facebook/facebook-ios-sdk) intentionally and don't have plans to restructure it.

**Comment by grabbou** [comment]
I think the first step to allow us linking fbsdk would be to add react-native to header search paths, so that we can link it without CocoaPods (the `rnpm` way) and later, to figure out how FBSDK would be installed (open ticket for native dependencies). Even if we implement linking of multiple projects (array), it won't work because of that.

**Comment by dzhuowen** [comment]
Make sense! And we can create rnpm fbsdk plugin for this. 
Adding the header search path will be easy but handling the dependency of FBSDK can be really messy IMHO.

**Comment by dzhuowen** [comment]
@grabbou What's your plan to implement this? 
It seems that considerate amount of changes is required (support linking multiple xcodeproj, link Facebook iOS SDK framework). I think it's much easier to create a rnpm-plugin specific to linking react-native-fbsdk.

**Comment by grabbou** [comment]
I'll try to implement nested paths today so that you can link a specific folder inside a package:
```
rnpm link react-native-fbsdk/iOS/core
```
and that should be all on our side :)

**Comment by grabbou** [comment]
Ok, turns out the implementation took 10 minutes, just to avoid an error from missing `json` in a nested folder. Apart from that it seems like an amazing undocumented feature 💃

**Comment by grabbou** [comment]
@dzhuowen the structure inside `fbsdk` should be actually (imo):
- core/ios|android
- login/ios|android

So that you can `rnpm link react-native-fbsdk/core` and have both platforms linked. Currently you'll have to run it twice.

**Comment by grabbou** [comment]
(this is closed as on our end it's done - please keep discussion so that we can think what's the best interface to use this feature on fbsdk side :) )

**Comment by dzhuowen** [comment]
Awesome. 
I will investigate the Android side for package reorganize.
But too bad this is not the end of setup.. react-native-fbsdk depends on Facebook-iOS-SDK framework. So we still need to link Facebook-iOS-SDK to the project.

**Comment by dzhuowen** [comment]
Current solution is manually linked the Framework.
Not sure if rnpm can do anything here.

**Comment by grabbou** [comment]
Yeah, we have that in plans and should land this month. For now, the only way is to follow the manual setup (more advanced users can probably just download FBSDK through CocoaPods, the rest should be fine with embedding it inside `vendor` folder that I've seen quite a few times already). 

I am still experimenting with Carthage in my projects to see if we can fit it into the pipeline (there's also some work being done to support Cocoapods), but I believe the long term goal is to just use `buck`.

**Comment by dzhuowen** [comment]
react-native-fbsdk 0.2.0 is up. We've switched to one single iOS project b/c for now setup simplicity is more important than flexibility :-). [react-native-fbsdk/issue119](https://github.com/facebook/react-native-fbsdk/issues/119).
