### ISSUE TITLE
findPlugins raise exception in node v6.0.0

### ISSUE THREAD

**Issue by holmescn** [rnpm/rnpm#149]
rnpm 1.6.2, node v6.0.0, findPlugins.js:16. The const pjson is defined in try block, so it become undefined in the block after the try-catch. I rewritten it in:

    const findPluginInFolder = (folder) => {
      let  pjson;
        try {
          pjson = require(path.join(folder, 'package.json'));
        } catch (e) {
          return [];
        }

        const deps = union(
        Object.keys(pjson.dependencies || {}),
        Object.keys(pjson.devDependencies || {})
    );

I am to lazy to create a PR ^_^.

**Comment by grabbou** [comment]
^_^
