### ISSUE TITLE
Command to include frameworks?

### ISSUE THREAD

**Issue by gnestor** [rnpm/rnpm#154]
I created a native module that depends on AudioToolkit.framework and Foundation.framework. Is it possible to use rnpm to add these frameworks to an Xcode project? Here are my [current installation instructions](https://github.com/gnestor/react-native-silent-switch#install):

* Install: `rnpm install react-native-silent-switch`
* Add AudioToolbox.framework and Foundation.framework to your project
  * Project Navigator > [YOUR PROJECT NAME] > Build Phases > Link Binary with Libraries

**Comment by grabbou** [comment]
I am working on it as a part of #122, thanks for your use-case, helps a lot when making an interface ;)
