### ISSUE TITLE
try-catch problem not completely solved.

### ISSUE THREAD

**Issue by holmescn** [rnpm/rnpm#155]
Perhaps since node v6.0.0, there are more strict syntax check about the variable scope. Last time I commit two issues that about variables defined in try-catch block and used later. But it seems there are more problems about this issue. Someone should go through the entire code to check this problem:
```js
try {
  const variable_defined_here = ...;
} catch (err) {
  log.warn(...);
  return ...;
}

if (variable_defined_here.some_property) { // <-- here will be an error.
  // Do something.
}
```

**Comment by Kureev** [comment]
We already moved this declarations out. Check out the newest version 😉

**Comment by grabbou** [comment]
Fixed in latest version, thanks for reporting! I think these are the last ones ;)
