### ISSUE TITLE
How do I link the correct library?

### ISSUE THREAD

**Issue by LeBlaaanc** [rnpm/rnpm#157]
Sorry if this is documented somewhere and I missed it. I have a project that is linking the wrong libraries `libStreamingKit.a` and `libStreamingKitMac.a` instead of `libRNStreamingKit.a`. Could anyone assist or PR with the proper way to do this? Thanks so much.

[https://github.com/LeBlaaanc/react-native-streamingkit](https://github.com/LeBlaaanc/react-native-streamingkit)

**Comment by grabbou** [comment]
Hey, interesting. Isn't that because we detect StreamingKit.xcodeproj instead of your RNStreamingKit one?

Try adding:
```json
{
  "rnpm": {
     "ios": {
        "project": "RNStreamingKit.xcodeproj"
    }
}
```

**Comment by LeBlaaanc** [comment]
I'll give this a go, can I PR a documentation update to include this to help out? I noticed the assets thing and figured it was something similar and your suggestion confirmed.

**Comment by grabbou** [comment]
Sure, feel free! Docs are always welcome :)

**Comment by LeBlaaanc** [comment]
@grabbou I gave this a go today. No luck :(

**Comment by LeBlaaanc** [comment]
I attribute this to my lack of experience with building xcode projects. From what I can tell I needed to "link binaries" under "build settings" instead of just dragging the StreamingKit.xcodeproj, also add to header search paths the library location. Should be all good, the package.json addition is unneeded once it it linked properly.
