### ISSUE TITLE
Support `rnpm install` for dependencies with multiple iOS/Android modules

### ISSUE THREAD

**Issue by Kureev** [rnpm/rnpm#159]
Currently, we can use `link` command to install a specific native module:
```
$ rnpm link react-native-fbsdk/iOS/core
````
But it seems that
```
$ rnpm install react-native-fbsdk/iOS/core
```
wouldn't work. We have to find a way how we can support this.

**Comment by Kureev** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Good idea!

Maybe we should check if a name is a sub-project and if yes - install the outer one (all the things), but link the scoped one?

In this case, the `rnpm install` would just `npm install react-native-fbsdk`.

Note: We have to make sure that this `@exponent/name` is a valid top-level.

**Comment by Kureev** [comment]
I have no private npm organizations to test `@domain/repo` pattern, can you add me to some, @grabbou ?

**Comment by grabbou** [comment]
Okay, I'll push a dummy iOS/Android under a fake name for the sake of testing :)

**Comment by Kureev** [comment]
I think we have the same issue in the RN repo (about private packages) - https://github.com/facebook/react-native/issues/8623. So I'm going to close this one to keep only one source of truth.
