### ISSUE TITLE
It seems something went wrong while linking. Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by cyphire** [rnpm/rnpm#161]
Followed instructions for installing realm.  When running 'rnpm link realm' following occurred:

[C:\Users\bcanin01\workspace\react\authentication]rnpm link realm
rnpm-link info Linking realm android dependency
rnpm-link info Android module realm has been successfully linked
rnpm-link info Linking realm ios dependency
rnpm-link info iOS module realm has been successfully linked
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues

Ran it again and got:

[C:\Users\bcanin01\workspace\react\authentication]rnpm link realm
rnpm-link info Android module realm is already linked
rnpm-link info iOS module realm is already linked
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues

**Comment by grabbou** [comment]
I think it's the issue with their command, @Kureev looks like maybe there was a breaking change in the interface? (seen few other issues re: that)

**Comment by Kureev** [comment]
> rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN

![image](https://cloud.githubusercontent.com/assets/2273613/15237094/e94e7bc8-1905-11e6-9a1b-6ac21bc1288c.png)

**Comment by Kureev** [comment]
I think it's related to Realm itself.

But to be safe, please, provide us you versions of:
- realm-js
- rnpm
- rnpm-plugin-link

and we'll try to investigate this.

cc @appden

**Comment by appden** [comment]
Admittedly, we have not done any testing on Windows yet, so it very much could be an issue with Realm. I'm curious though if `rnpm` should even try to link iOS stuff on any non-Mac platform?

As for the error itself, I googled `spawn UNKNOWN` and it seems pretty common for issues with running Node modules on Windows, but nothing popped out to me as the obvious answer for this.

@Kureev That's the scariest photo I've ever seen. Thanks for that.

**Comment by cyphire** [comment]
Sorry - should have gotten back sooner, must have been an environmental issue, closing.

**Comment by npomfret** [comment]
I've got the same issue - how did you fix it?

**Comment by cyphire** [comment]
My problem was related to my environment.  Non issue.  Make sure you
install realm in an admin console, if it fails just install again until
dependencies resolved.

If I remember the rnpm had issue on 5th link but realm worked perfectly.
Tell me if it works...

**Comment by hhashmi** [comment]
Tried to install realm on windows by following
https://realm.io/docs/react-native/latest/#getting-started

rnpm link realm (tried it 2 - 3 tiems)
gives following output

rnpm-link info Android module realm is already linked
rnpm-link info iOS module realm is already linked
rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN

Please file an issue here: https://github.com/rnpm/rnpm/issues

rnpm --version : 1.9.0
node --version : 4.4.7
react native :+1:  0.30.0

Please guide me how you guys resolved this issue.

**Comment by Fanda36** [comment]
I solved your problem @hhashmi with [https://github.com/realm/realm-js/issues/477](this) issue. (manual adding plugin and recompiling project) Now work it me fine.
