### ISSUE TITLE
It seems something went wrong while linking. Error: Expected "/*", "//" or "{" but "<" found

### ISSUE THREAD

**Issue by LeBlaaanc** [rnpm/rnpm#163]
I'm not sure where to start to troubleshoot this... my package.json looks okay?

**Comment by LeBlaaanc** [comment]
Figured it out, something that was in my node_modules giving it an issue.

**Comment by grabbou** [comment]
Try opening your project with Xcode. Sometimes your project gets converted to xml (typically by CocoaPods) and needs to be reopened with Xcode so it converts it automatically to the format we can parse.

**Comment by ghamaide** [comment]
I have the same issue, how did you solve it ?
