### ISSUE TITLE
MainActivity.java: custom patching

### ISSUE THREAD

**Issue by jdeniau** [rnpm/rnpm#164]
Hi,

Sorry if it's already possible but I did not find anything on how to do it.

Some packages have specific patch to apply in `MainActivity.java` (and maybe the same for ios ?).

For example [this project](https://github.com/gijoehosaphat/react-native-keep-screen-on#in-mainactivityjava-add-the-following-lines) needs to pass `this` as a parameter, but rnpm will do this:
```diff
- new KeepScreenOnPackage(this) # wanted 
+ new KeepScreenOnPackage() # with `rnpm link`
```

Is it possible to do something to update this behavior, maybe directly in the package ?

Thank you

**Comment by Kureev** [comment]
Hey @jdeniau,

I've already answered similar question: https://github.com/rnpm/rnpm/issues/115#issuecomment-200249027

**Comment by jdeniau** [comment]
Oh great thank you, I did not found that :)
