### ISSUE TITLE
RNPM found a wrong project

### ISSUE THREAD

**Issue by Arthraim** [rnpm/rnpm#165]
Hi, guys

For some reasons, we have other projects in `RN_REPO/ios/dependencies`. Since `findProject.js` easily pick the first one of all found projects, it actually link changes to a wrong project.

I'm thinking can we at least add an argument to allow user to specify project file such as
```bash
rnpm install SOMETHING --proj MY_PROJECT_NAME
```
or, can we say the deeper the .xcodeproj file placed the fewer chances it will be the right one?

**Comment by grabbou** [comment]
Hey,
You can add:
```json
"rnpm": {
   "ios": {
      "project": "ios/path/to/My.xcodeproj"
   }
}
```
to your package.json to bypass the `xcodeproj` glob.

PS. It works for both dependencies and projects as well.

**Comment by Arthraim** [comment]
Great, didn't notice. Thanks! @grabbou 
Closing this :D
