### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by simman** [rnpm/rnpm#166]
rnpm-link info Android module @remobile/react-native-toast is already linked
rnpm-link ERR! It seems something went wrong while linking. Error: Maximum call stack size exceeded
Please file an issue here: https://github.com/rnpm/rnpm/issues

**Comment by magrinj** [comment]
@simman you find why ?

**Comment by simman** [comment]
yeah，I manually remove the xcode project depends on, and then re-use RNPM link.

**Comment by magrinj** [comment]
Ok thanks, I find the solution just after my message and I do the same :)
