### ISSUE TITLE
rnpm link grpc does not handle native transitive deps

### ISSUE THREAD

**Issue by ZhangBanger** [rnpm/rnpm#167]
After linking the node `grpc` lib, I'm still getting 
```
__dirname is not defined
```
after the import / require

**Comment by grabbou** [comment]
Mind providing a bit more details? Is `grpc` a react-native plugin that you are trying to link or just a normal module?

**Comment by ZhangBanger** [comment]
I just realized that rnpm is dealing with iOS/Android native modules, not node modules with native components - my mistake!
