### ISSUE TITLE
How to build a library that can be linked with rnpm?

### ISSUE THREAD

**Issue by tonyxiao** [rnpm/rnpm#170]
I can't find any docs on this anywhere. But how do I build a library that can can be consumed via `rnpm`?

**Comment by Kureev** [comment]
Hey! Most of the libraries can be linked with rnpm "by default", you don't need to perform any additional steps.

**Comment by Kureev** [comment]
There are few exceptions (like if you want to link fonts), but they are all described in the readme.

**Comment by grabbou** [comment]
Yup, as long as you have `xcodeproj` in your library and `android` folder, we will work it automatically.

**Comment by tonyxiao** [comment]
Whoa that's pretty magical. Where do I look under the hood to understand how the magic works?

**Comment by grabbou** [comment]
Check this file https://github.com/rnpm/rnpm/blob/master/src/config/index.js and just follow the referenced functions :)

**Comment by voidException** [comment]
on the iOS  platform rnpm  just  let the  project know your library, so your library  cant find the React Native  header  files, you should  link  by hand,
http://reactnative.cn/docs/0.26/linking-libraries-ios.html#content

**Comment by tonyxiao** [comment]
Found this in `react-native-code-push`'s repo `package.json`. Seems that library authors can choose to interact with `rnpm`. Where is this documented?
![image](https://cloud.githubusercontent.com/assets/696842/15808042/50cc1304-2b22-11e6-9a9b-bbc4f4a3ef24.png)

**Comment by Kureev** [comment]
Not all of them. I'm planning to improve rnpm's docs section once we finish merging it into react-native

**Comment by grabbou** [comment]
Here https://github.com/rnpm/rnpm#params. For now, only `packageInstance` is supported as a param. We haven't found any other good places yet, so feature requests welcome :)

**Comment by Kureev** [comment]
I think this one can be closed.
