### ISSUE TITLE
Doesn't work for transitive dependencies?

### ISSUE THREAD

**Issue by Secretmapper** [rnpm/rnpm#173]
I'm writing a module (A) that requires another module (B). B has assets installable by `rnpm link`.

If I as an app author use module (A), running `rnpm link` doesn't seem to install the assets of B. Perhaps a workaround right now is to simply install B's native dependencies explicitly, but just wondering if this is intended behaviour.

**Comment by Kureev** [comment]
Hi @Secretmapper! If you're talking about native dependencies, you're right. We don't provide this functionality yet (but we have an intention to implement it). Currently, you can make a `postlink` hook (see README) which will run an installation process for your dependencies.

**Comment by grabbou** [comment]
Yeah, that's how it works for now, mainly because module `B` should be linked with project `A` and that's how it's done in most cases if I am not wrong (iOS). With Android, `gradle` will handle all these things for us anyway.

**Comment by Kureev** [comment]
I think there's nothing bad in using `postlink` hooks for these purposes

**Comment by Secretmapper** [comment]
Hello guys, thanks for the quick feedback!

What was actually weird was I tried adding `rnpm link` on module A, thinking that running `rnpm link` on the actual app would propagate the libraries to the actual app, but it doesn't seem to work (module A's xcodeproj does get added on the app, but it's dependency libraries still seem to be missing)

@Kureev If you don't mind, can you write out a quick sample in using `postlink`s once you have the time? I don't have native ios experience, so I'm not particularly sure how to create the hook.

How would it look like to use `postlink` hooks to implement this right now?

**Comment by Kureev** [comment]
It literally one-to-one as `npm scripts`: https://github.com/rnpm/rnpm#commands.

Can you provide some real-world example? I'll try to sketch it.

**Comment by Secretmapper** [comment]
I'm working on extracting a part of my recent project to a module, which is an epub reader for react-native.

To render the epub templates, I'm making use of https://github.com/alinz/react-native-webview-bridge and https://www.npmjs.com/package/react-native-zip-archive. I'm unsure of what to put in my module's `postlink` to add their dependencies.

Thanks again!

**Comment by Kureev** [comment]
@grabbou do you have any snippet to add `libz` to the project?

**Comment by grabbou** [comment]
We are going to support it thanks to @appden PR if I am not wrong?

**Comment by Kureev** [comment]
Yeah, true. But it's not merged yet, right?

**Comment by PC123PC** [comment]
Hi Arian @Secretmapper, please get in touch with me with regards to the Salescamp project - I don't understand why you've just stopped replying to messages for 2 months even after you've received payment and signed a contract? http://arianv.com

**Comment by grabbou** [comment]
@PC123PC I've removed your comment, please sort out any business inconveniences with @Secretmapper outside this repo, thank you :)

**Comment by appden** [comment]
@Secretmapper @Kureev until my PR is merged and released, you can accomplish automatically linking `libz` through a postlink script. [Here](https://github.com/realm/realm-js/blob/master/scripts/rnpm-postlink.js) is the one I created for Realm.

**Comment by grabbou** [comment]
I am planning to review it tomorrow, merge and release, so if you don't mind waiting an extra day, thats awesome!

**Comment by Kureev** [comment]
Thanks for sharing your script, @appden! I think that supposed to solve the initial problem 'till we merge your PR in 😉
