### ISSUE TITLE
rnpm init - initialize a new third party project

### ISSUE THREAD

**Issue by ajwhite** [rnpm/rnpm#177]
Creating third party modules and components is a very hands on process from my experience. 

It would be really nice to simply run `rnpm init ProjectName` and have the boilerplate scaffolded out. 

I would imagine a structure like so

```
ios/
android/
package.json
```

**Comment by Kureev** [comment]
I usually use `react-native init` to start init a third-party module. But I agree, there should be something better for this purpose. 

But you can create your own scaffolding tool and expose it as a plugin to rnpm. So, people can use it like this:

```
$ npm install rnpm-plugin-init
$ rnpm init <NameOfModule>
```

cc @grabbou @mkonicek

**Comment by ajwhite** [comment]
Oh great point

**Comment by Kureev** [comment]
I think we'll eventually tackle it, but we have no vision yet. Feel free to propose an idea if you have something in mind 😉 Closing for now.

**Comment by ajwhite** [comment]
As `rnpm` is very plugin based, I think working on a third party plugin is the best way to introduce a new idea. Will start there 😄

**Comment by Kureev** [comment]
Let me know if you need any kind of assistance!
