### ISSUE TITLE
It seems something went wrong while linking. Error: Expected ";" but " " found.

### ISSUE THREAD

**Issue by alexHlebnikov** [rnpm/rnpm#178]
Hi! 

I'm using Firebase Analytics in my Rect Native iOS app. 
Today I'm updated RN from 0.25.1 to 0.28 and now I can't build my app with errors about Firebase in debugger. 

So I'm tried to reinstall RN analytics component (https://github.com/evollu/react-native-firebase-analytics) and link it again. But when I'm doing ```rnpm link react-native-firebase-analytics``` I'm getting this error: ```It seems something went wrong while linking. Error: Expected ";" but " " found.```

And when I'm trying to unlink react-native-firebase-analytics, I'm getting this error:  ```/usr/local/lib/node_modules/rnpm/node_modules/xcode/lib/parser/pbxproj.js:1835
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
      ^
SyntaxError: Expected ";" but " " found.```

Is there a way to fix my issue?

**Comment by Kureev** [comment]
Seems we need to follow up on this, @grabbou

**Comment by alexHlebnikov** [comment]
I've fixed my issue! 

I used changes from this PR: https://github.com/alunny/node-xcode/pull/96 and them helped.

**Comment by Kureev** [comment]
Awesome, glad you've figured out!
