### ISSUE TITLE
Add new key values / modify existing key value pair in info.plist file of iOS apps by using swift.

### ISSUE THREAD

**Issue by eldhoseelias** [rnpm/rnpm#181]
i create a iOS app, and i integrated 3 social login like Facebook,linkedin,google plus into my iOS app.
At the time of configuration i added some key and values in info.plist file of my iOS app.
Now i want to add that key value pair in a programmatic way ...
is it possible..?

**Comment by Kureev** [comment]
Yes, you can create a postlink hook, as it described in the README. 
In this postlink hook you can use PLISTBUDDY to have an easy access to your info.plist file!

**Comment by eldhoseelias** [comment]
it is possible to edit info.plist file after deploying an app in app store
