### ISSUE TITLE
Scoped Modules

### ISSUE THREAD

**Issue by migueloller** [rnpm/rnpm#182]
Currently `rnpm` doesn't work with [scoped modules](https://docs.npmjs.com/misc/scope).

Scoped modules are usuall organized the following way in the `node_modules` folder:

`package.json`:
```json
{
  "dependencies": {
    "@somescope/somepackagename": "^1.0.0",
    "@somescope/someotherpackagename": "^1.0.0"
  }
}
```
```
node_modules/
`- @somescope/
   |- somepackagename/
   `- someotherpackagename/
```

`rnpm` checks for a `package.json` inside the `@somescope` folder, which causes the following error:
```
Error: Cannot find module '~/path/to/package/node_modules/@somescope/package.json'
```

**Comment by Kureev** [comment]
Thanks for your issue. I'll take a look.

**Comment by Kureev** [comment]
Further discussion will be available here: https://github.com/facebook/react-native/issues/8623
