### ISSUE TITLE
RN .29 Java MainApplication

### ISSUE THREAD

**Issue by tuneZola** [rnpm/rnpm#186]
For RN .29, All the Java dependencies are being moved to the MainApplication file and not the MainActivity file. I am still getting items being linked to the Activity file, so I assume that this change has not been made yet?

**Comment by grabbou** [comment]
Will be soon cherry-picked into .29 and released as a 0.29.1 inside react-native. We no longer plan to release rnpm itself (unless our merge PR gets stuck)

CC: @Kureev
