### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by sankhadeeproy007** [rnpm/rnpm#187]
Hi, great library. Very useful. I have a doubt. I'm working on [NativeBase](https://github.com/GeekyAnts/NativeBase), and I'd like to have fonts as a variable. I did go through the readme and there was a reference to fonts, however I'm not sure how the copying would be done. Would it download the `.ttf` files automatically and copy them over or do we have to manually add the `.ttf` files in our project root?

**Comment by Kureev** [comment]
You can specify an [assets folder](https://github.com/rnpm/rnpm#advanced-usage) for your static content (like fonts etc). It'll automatically copy(Android)/reference(iOS) them to your project. Is it what you were looking for?

**Comment by sankhadeeproy007** [comment]
Okay I get it now. Where should the assets folder ideally be located?

**Comment by sankhadeeproy007** [comment]
Never mind, I figured it out. Thanks!

**Comment by sankhadeeproy007** [comment]
@Kureev I tried with the following structure. The Fonts folder in my package root and the package.json as given in the screenshot. It didn't copy the font files and neither updated info.plist. What am I doing wrong? ![screen shot 2016-07-12 at 6 18 13 pm](https://cloud.githubusercontent.com/assets/10998047/16767431/1051f1f6-485d-11e6-839a-aa6d8b51b3f1.png)

**Comment by Kureev** [comment]
What kind of fonts do you have? .ttf?

**Comment by Kureev** [comment]
see https://github.com/rnpm/rnpm-plugin-link/blob/f20f56e4894e4a716147766276ab4328482d9503/src/groupFilesByType.js

**Comment by sankhadeeproy007** [comment]
I have `.ttf` and a few `.ttc`. But even the `.tff` files aren't getting copied.

**Comment by sankhadeeproy007** [comment]
I did work fine on a new project after  a fresh init. Still couldn't figure out what went wrong in the previous project though.
