### ISSUE TITLE
Not working on 0.29.1

### ISSUE THREAD

**Issue by jbrodriguez** [rnpm/rnpm#189]
I'm not sure why I'm getting this error.

I have installed v1.9.0 and RN 0.29.1

If I run react-native link react-native-fabric, I get

```javascript
rnpm-link info Linking react-native-fabric android dependency
rnpm-link ERR! It seems something went wrong while linking. Error: path must be a string
Please file an issue here: https://github.com/rnpm/rnpm/issues
/Users/Guest/code/testapp/app/node_modules/promise/lib/done.js:10
      throw err;
      ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at applyPatch (/Users/Guest/code/testapp/app/node_modules/react-native/local-cli/rnpm/link/src/android/patches/applyPatch.js:6:29)
    at registerNativeAndroidModule (/Users/Guest/code/testapp/app/node_modules/react-native/local-cli/rnpm/link/src/android/registerNativeModule.js:23:3)
    at /Users/Guest/code/testapp/node_modules/react-native/local-cli/rnpm/link/src/link.js:43:5
    at process._tickCallback (node.js:406:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3
```

If I run rnpm link, it says everything's ok, but MainApplication.java is not modified

The same error with react-native-device-info.

It populates settings.gradle and build.gradle, it's just MainApplication.java that's missing.

**Comment by Kureev** [comment]
see
https://github.com/rnpm/rnpm/issues/184
https://github.com/rnpm/rnpm/issues/185
https://github.com/rnpm/rnpm/issues/186

**Comment by jbrodriguez** [comment]
@Kureev, 0.29.1 was released and this is supposed to be fixed there.

https://github.com/facebook/react-native/releases/tag/v0.29.1

I have RN 0.29.1, so it should work, but it's not happening for me.


Can you please reopen the issue and check it ?

**Comment by Kureev** [comment]
Have you used `react-native link`? This repo has been merged into react-native and it literally lives it's last days. I don't think we release any more releases on rnpm (but as I said, it's part of the react-native now, so please, check it out!).

**Comment by jbrodriguez** [comment]
yes, that's exactly what I did

```bash
$ react-native link react-native-fabric
$ react-native link react-native-device-info
```

none of them are updating MainApplication.java

I'll try to debug further, but I think there may be a legit issue here.

**Comment by hanswilw** [comment]
@jbrodriguez, I am having the same problem - though I believe that line 30 and 35 in [reigsterNativeModule.js](https://github.com/facebook/react-native/blob/214a41d62af6c752bf34e40bc0b046790a009e3d/local-cli/rnpm/link/src/android/registerNativeModule.js) wasnt adjusted to the change. When adjusting these the MainApplication.java is patched, but the import line fails. As of now I am just manually adding it.

**Comment by Kureev** [comment]
ref: https://github.com/facebook/react-native/pull/8612

**Comment by Kureev** [comment]
hotfix: https://github.com/facebook/react-native/pull/8807

**Comment by aksharpatel47** [comment]
Faced this problem on 0.30 too when linking realm.

**Comment by Kureev** [comment]
Please, use "react-native link" instead.
