### ISSUE TITLE
Ability to configure copying of fonts in app projects

### ISSUE THREAD

**Issue by cbrevik** [rnpm/rnpm#19]
Ref discussion at #18.

What I would like to see is the ability to configure assets for my own app, (i.e. not third-party packages), and have that added to the iOS/Android-projects of my app with ```rnpm link``. Or through some other mechanism in that chain.

One paint point this would solve is when you use ```react-native upgrade``` it removes the custom fonts from your app iOS/Android projects (along with third party native modules).

**Comment by grabbou** [comment]
If that's only the case of `rn upgrade` we might handle that in our `rnpm-plugin-react-cli` that will provide a bridge to these methods so you don't have to use two clis. I am going to publish that plugin by the end of the week.

CC: @brentvatne @mkonicek
