### ISSUE TITLE
SyntaxError: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

### ISSUE THREAD

**Issue by zicjin** [rnpm/rnpm#191]
react-native link react-native-vector-icons
rnpm-link info Linking react-native-vector-icons android dependency
rnpm-link info Android module react-native-vector-icons has been successfully linked
rnpm-link ERR! It seems something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.
Please file an issue here: https://github.com/rnpm/rnpm/issues

C:\work\sloth-app\node_modules\promise\lib\done.js:10
      throw err;
      ^
 SyntaxError: Expected "/* Begin ", "/* End ", "\"" or [A-Za-z0-9_.] but "<" found.

**Comment by grabbou** [comment]
@Kureev I am thinking we should print out an information that users should just open project with `xcode` and try again /this is something that happens a lot/

**Comment by zicjin** [comment]
Indeed, it is xcodeproj issus caused by git merge
