### ISSUE TITLE
It seems something went wrong while linking. Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by hhashmi** [rnpm/rnpm#192]
Tried to install realm on windows by following
https://realm.io/docs/react-native/latest/#getting-started

rnpm link realm (tried it 2 - 3 tiems)
gives following output

> rnpm-link info Android module realm is already linked
> rnpm-link info iOS module realm is already linked
> rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
> 
> Please file an issue here: https://github.com/rnpm/rnpm/issues

rnpm --version : 1.9.0
node --version : 4.4.7
react native : 0.30.0

Please guide me how you guys resolved this issue. (Ref: closed issue: 161)

**Comment by hhashmi** [comment]
Same thing is happening when I try it with couchbase lite.
Following 
https://github.com/couchbaselabs/react-native-couchbase-lite

**Comment by hhashmi** [comment]
Got it resolved by
Close Android Studio and simulator
Remove APKs from android\app\build\outputs\apk

Start simulator and every thing is ok.

this issue may appear again, follow same steps and happy coding

**Comment by Kureev** [comment]
Nice @hhashmi! 

I'm sorry for not responding in time. Glad to hear you found a way to fix your issue! Sounds like a good improvement to documentation, I think some other people may encounter it as well. Do you want to add a README block to describe the error and a way you solved it?
