### ISSUE TITLE
react-native-lock: It seems something went wrong while linking

### ISSUE THREAD

**Issue by dwilt** [rnpm/rnpm#193]
Getting this:

```
rnpm-link info Android module react-native-lock is already linked 
rnpm-link ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/dwilt/Projects/GJS/gjs-app/ios/AirshipKit/AirshipKit.xcodeproj/project.pbxproj' 
Please file an issue here: https://github.com/rnpm/rnpm/issues 
```
 while trying to run 
```bash
rnpm link react-native-lock
```

**Comment by stantoncbradley** [comment]
I'm having issues with react-native-lock as well. didn't get this error, but when i try logging in through facebook app my app just hangs.  maybe unrelated, maybe not?

**Comment by Kureev** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Hey @dwilt, we will be looking into this issue right after we merge our `rnpm` into react-native which shouldn't take more than a day now.

**Comment by dwilt** [comment]
@grabbou thanks for the update. that would be fantastic as a project I'm working on requires this!

**Comment by Kureev** [comment]
In the meanwhile: could you check if `/Users/dwilt/Projects/GJS/gjs-app/ios/AirshipKit/AirshipKit.xcodeproj` exists? If not, use rnpm config to point to the correct xcodeproj

**Comment by dwilt** [comment]
@Kureev It does exist. What doesn't is the `.pbxproj` inside of it:

<img width="268" alt="screenshot 2016-07-29 07 22 06" src="https://cloud.githubusercontent.com/assets/1065539/17251349/38ee6ef2-555d-11e6-9fb3-66b87566c33a.png">

This is after only running `npm install --save react-native-lock`

**Comment by Kureev** [comment]
It looks a bit odd. Seems it's not a part of the module. Probably, we should file an issue in `react-native-lock` repo. 

@grabbou?

**Comment by dwilt** [comment]
Already done: https://github.com/auth0/react-native-lock/issues/75

**Comment by dwilt** [comment]
Verified this works with the a blank React Native project scaffold `react-native init TestAuth`. The issue was an issue with UrbanAirship (the error referenced AirshipKit) and nothing to do with `react-native-lock`.
