### ISSUE TITLE
Linking fails after renaming project

### ISSUE THREAD

**Issue by gohanman** [rnpm/rnpm#194]
I renamed a project by changing `name` in `package.json` and running `react-native upgrade`. This generated a new set of subdirectories under `ios`.

Now when I run `rnpm link` I get this. It does not seem to matter which particular package I'm trying to link.
```
$ rnpm link react-native-maps
rnpm-link info Android module react-native-maps is already linked
rnpm-link ERR! It seems something went wrong with linking. Error: ENOENT: no such file or directory, open '/Users/andy/AwesomeProject/ios/AwesomeProject.xcodeproj/project.pbxproj'
Please file an issue here: https://github.com/rnpm/rnpm/issues
```

`AwesomeProject` was the previous name of the project. I imagine there's a cached information problem somewhere but grepping through node_modules for `AwesomeProject.xcodeproj` turns up nothing.

**Comment by Kureev** [comment]
Hey @gohanman!

I think it's not about cached information, but about first xcodeproj that rnpm finds in your project folder. Can it be that you have `ios/AwesomeProject.xcodeproj` and `ios/<NewProjectName>.xcodeproj`?

**Comment by gohanman** [comment]
That indeed seems to do it. Thanks!
