### ISSUE TITLE
Architecture proposal

### ISSUE THREAD

**Issue by Kureev** [rnpm/rnpm#5]
This is an architecture proposal to clarify the structure of upcoming files.

## Binary
Runnable files should be located under the `bin` folder

## Source
Program sources should be located under the `src` folder

## Actions
All CLI actions should be stored in `src/actions` folder, each file represents one action

## Android / iOS
Android and iOS related files should be putted under `src/android` & `src/ios` folders. Inner structure may vary.

## Plugins
All installed plugins should be located as a normal npm package under `node_packages` folder
**We need to move your validation script out to standalone repo, @grabbou!**

## Helpers / Utils
All kind of helpers / utils / tools which are not directly related to the application logic should be stored at `src/utils`

**Comment by ptmt** [comment]
*Tests* section in proposal is missing, I'm happy to send pull request with a few tests. Also, what's your opinion about Flow?

**Comment by Kureev** [comment]
I'm fine with flow, but I want to keep it without preprocessors

**Comment by grabbou** [comment]
Yep, we wanted to avoid pre processors given the fact Node support for ES6 is quite good.

**Comment by ptmt** [comment]
I see, I mean Flow comments syntax:

```js
const getProducts/*:Array<Product>*/ = (project/*:PbxProject*/) => {
  return project
    .pbxGroupByName('Products')
    .children
    .map(c => c.comment)
    .filter(c => c.indexOf('.a') > -1);
};
```
 But sure, there is always tradeoff with readability.

**Comment by Kureev** [comment]
Well, for now I'd prefer readability. Maybe it's "nice to have", but I would definitely postpone it until some urgent stuff will be done

**Comment by grabbou** [comment]
I never been a huge advocate of type checking in Javascript, nice hints, but I'd rather see them in `jsdoc` above the method definition for now :dancer:

**Comment by Kureev** [comment]
I'm going to close it due to big difference with a plugins architecture we have now. Seems like it doesn't make that much sense.

**Comment by grabbou** [comment]
Yeah, changed for better :)
