### ISSUE TITLE
Why not support Microsoft CodePush?

### ISSUE THREAD

**Issue by idibidiart** [rnpm/rnpm#50]
The reason I prefer it over AppHub is because it is free.

I know it's by invite only but it wasn't hard to request and get an invite.

**Comment by grabbou** [comment]
AppHub is developed as a plugin by @ptmt and there's no core team work on that being done yet. We encourage the community to cover `CodePush` as well, but since I am not using it in production, I'd rather see somebody else working on that.

**Comment by Kureev** [comment]
You can also ping me if you need any help with it!
