### ISSUE TITLE
Linking react-native-device-info android dependency failed

### ISSUE THREAD

**Issue by xxsnakerxx** [rnpm/rnpm#53]
Error: ENOENT: no such file or directory, open 'app/android/app/src/main/java/com/my/app/MainActivity.java'
    at Error (native)
    at Object.fs.openSync (fs.js:585:18)
    at Object.fs.readFileSync (fs.js:432:33)
    at app/node_modules/rnpm-plugin-link/src/android/registerNativeModule.js:11:12
    atapp/node_modules/lodash.flowright/index.js:35:42
    at registerNativeAndroidModule (app/node_modules/rnpm-plugin-link/src/android/registerNativeModule.js:87:8)
    at app/node_modules/rnpm-plugin-link/src/link.js:57:7
    at Array.forEach (native)
    at Object.link (app/node_modules/rnpm-plugin-link/src/link.js:54:16)
    at Command.runAction (app/node_modules/rnpm/bin/cli:27:15)

__npm__ `3.5.2`
__rnpm__ `1.3.4`
__RN__ `0.16`

**Comment by Kureev** [comment]
if you have a custom path to MainActivity.java, you can specify it in `rnpm` config section of package.json:
```json
"rnpm": {
  "android": {
    "mainActivityPath": "path/to/MainActivity.java"
  }
}
```

**Comment by xxsnakerxx** [comment]
The error message has right path to MainActivity.java and android project has no any changes after generating.

**Comment by Kureev** [comment]
Well, the error says ENOENT, so it seems file is missing. 
Can I reproduce this issue by running `rnpm link` after scaffolding a new react-native project?

**Comment by xxsnakerxx** [comment]
HO-HO-HO, I was wrong :-) paths are different...

__error__ `/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/app/src/main/java/com/coloreight/qplaces/MainActivity.java`

__real__ `/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/app/src/main/java/com/qplaces/MainActivity.java`

but whose the bug is?

**Comment by xxsnakerxx** [comment]
seems yours, because RN doesn't ask bundle identifier when init 🤔

**Comment by xxsnakerxx** [comment]
And I've found bundle identifier in my project in only one place, it's xcodeproj

**Comment by Kureev** [comment]
We can also get it from Android manifest file (package property with `.` replaced by `/`). The question is why your manifest file contains a different path...

**Comment by grabbou** [comment]
@xxsnakerxx please open up your AndroidManifest.xml and update value to reflect real path in file system, because it's not `com.qplaces` but `com.coloreight.qplaces` or something (am I right?). Anyway, your folder structure should mirror package name in order for the `rnpm` to work flawlessly.

**Comment by Kureev** [comment]
@grabbou well, I can also try to search for `MainActivity.java` as we do it for manifest file

**Comment by grabbou** [comment]
Yep, the question is - is it really that necessary? I mean - in almost all cases folders should reflect package name - I think that's industry standard in Java. But since I am not a master in that matter, I am leaving that open to you.

**Comment by xxsnakerxx** [comment]
AndroidManifest.xml -> `package="com.qplaces"`
MainActivity.jaja -> `package com.qplaces;`

**Comment by Kureev** [comment]
Android part works independent from iOS part. Can you share this project with me and/or @grabbou?

**Comment by xxsnakerxx** [comment]
I can't because it's private... but I've found something interesting...

That's output `console.log(project)` [from here](https://github.com/rnpm/rnpm-plugin-link/blob/master/src/link.js#L34)

```javascript
{ assets: [ '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/resources/fonts/qfont.ttf' ],
  ios:
   { sourceDir: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/_backup/cordova/platforms/ios/CordovaLib',
     folder: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client',
     pbxprojPath: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/_backup/cordova/platforms/ios/CordovaLib/CordovaLib.xcodeproj/project.pbxproj',
     projectPath: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/_backup/cordova/platforms/ios/CordovaLib/CordovaLib.xcodeproj',
     projectName: 'CordovaLib.xcodeproj',
     libraryFolder: 'Libraries' },
  android:
   { sourceDir: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/app',
     folder: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client',
     buildGradlePath: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/app/build.gradle',
     settingsGradlePath: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/settings.gradle',
     assetsPath: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/app/src/main/assets',
     mainActivityPath: '/Users/xxsnakerxx/Works/Eris/QPlaces/Client/android/app/src/main/java/com/coloreight/qplaces/MainActivity.java' 
  } 
}
```

I have folder `_backup` which contains __cordova__ project with ios and android platforms and that android project has manifest(__/Users/xxsnakerxx/Works/Eris/QPlaces/Client/_backup/cordova/platforms/android/AndroidManifest.xml__) with defined package `com.coloreight.qplaces`

**Comment by xxsnakerxx** [comment]
I renamed `_backup` to `z_backup` and all works fine, but I think need show warning if found multiple projects (+1 here https://github.com/rnpm/rnpm/issues/55)...

**Comment by Kureev** [comment]
Yeah, that was an issue! I think we need to make an option to manually exclude some folders from search. What do you think, @grabbou? I propose something like this:
```json
"rnpm": {
  "ignore": ["**/some", "**/custom", "**/folders"]
}
```

**Comment by xxsnakerxx** [comment]
Or better way IMHO, rnpm should have default config with paths to projects (__ios__ -> `RN_ROOT/ios`, __android__ -> `RN_ROOT/android`)... If user has non standard folders structure, he can set path in pjson like here https://github.com/rnpm/rnpm/issues/53#issuecomment-164560830

**Comment by grabbou** [comment]
You cannot set android folder for now as it expects it to be either `android` or `app/android` (that will be improved soon). 

I think we can blacklist `cordova` in globbing for manifest.xml and that should solve the issue?

**Comment by Kureev** [comment]
@grabbou I'm afraid in this case we need to blacklist a lot of different things. Better to keep it up to the user, imo

**Comment by grabbou** [comment]
Agreed. I have a small solution to that, @xxsnakerxx you can just 
```js
rnpm: {
   android: {
      sourceDir: '/my/custom/folder/that/works`
  }
}
```
and a small change I am making will make that working

**Comment by xxsnakerxx** [comment]
Ok. I will try that, but I'm little bit confused, why __React Native Package Manager__ doesn't know default paths to platforms? :-) I think rnpm should search there first time... and if nothing was found then should search everywhere and choose first match...

**Comment by grabbou** [comment]
The default path to platform is `android` or `android/app`. It's just that we were looking for `AndroidManifest.xml` in a wrong folder ;) Generally, there's nothing like a default path yet, especially in Java where almost every single module has its own structure.

For iOS - it's much more better since we only care about one file :)

**Comment by grabbou** [comment]
Could you please check if this still occurs? @xxsnakerxx I think recent changes have fixed the issue we were talking about here.

**Comment by Kureev** [comment]
Closed due to lack of feedback
