### ISSUE TITLE
Warn when multiple xcodeproj found

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm#55]
As per discussing with @jsierles, we should warn when multiple projects found in that method https://github.com/rnpm/rnpm/blob/master/src/config/ios/findProject.js#L29 and point out we are returning the first match (and optionally include tips how to change that).

Also, when doing this -> add in test case for `IntegrationTests` and whatever that contains `tests` to make sure it's skipped from search.

PS. @Kureev how should we print `warn` ? Easiest way is to print directly from `findProject` but for some reason it does not seem right to me.

**Comment by Kureev** [comment]
I did exactly the same for manifest file. In my case I had a multiple manifest files inside `builds` folder. So, you idea have a :+1: from me.

P.S. About `warn` - I'm not sure. Let's say if we'll face this issue again, we'll discuss how to solve it. Now it just looks to me like we forgot to add some folder to ignore.

**Comment by grabbou** [comment]
Yeah, it's very unlike case. I believe that with latest PR #56 that should not happen again.

**Comment by grabbou** [comment]
Consider again after #67 gets to next stage.

**Comment by grabbou** [comment]
Fixed more edge cases in #74. It is very unlikely to happen again, but we can re-open if more people get affected by that. So far, seems like glob works quite well.
