### ISSUE TITLE
.rnpmrc proposal

### ISSUE THREAD

**Issue by Kureev** [rnpm/rnpm#6]
I think we need to support some custom actions in our prototype.

##### Example `.rnpmrc` config file for `react-native-vector-icons`:
```json
{
  "name": "react-native-vector-icons",
  "android": {
    "package": "com.oblador.vectoricons.VectorIconsPackage"
  },
  "ios": {
    "some": "options"
  },
  "instructions": {
    "unix": [
      "cp -R $ROOT/Fonts $TARGET_IOS/path/to/assets"
    ],
    "win": [
      "xcopy $ROOT/Fonts $TARGET_IOS/path/to/assets /s/h/e/k/f/c"
    ]
  }
}
```

**Comment by mkonicek** [comment]
Side note: You could make this "convention-over-configuration" as much as possible. For example, we can ask module authors to always follow exactly the same folder structure (and even naming when appropriate) to keep thing very simple: https://github.com/garysye/react-native-android-geolocation

**Comment by Kureev** [comment]
I like this idea. If @grabbou will agree to remove detection part, I'll make it

**Comment by grabbou** [comment]
Good idea but for now let's keep the detection since we cannot force all package developers to adjust to that. Maybe at some point it's going to be a good move, but since detection works quite well and it's few lines I'm fine with having it.

**Comment by grabbou** [comment]
On a side note I need to send a PR to config so it detects android also when there's no android folder present (like in above example).

**Comment by Kureev** [comment]
Well, for that purposes we can have a config. All Android files my be stored in a slightly different folders, I don't want to have 3+ file detections (and that's besides the fact we have 2 x `builde.gradle` files). My opinion on this is that developers should either adjust their folder structure to suggested by react native team, or just add a config.

**Comment by grabbou** [comment]
As I said - I want this tool to work with the maximum number of packages possible without any extra action by package authors. The detection has only 3 super trivial methods and so far does the job pretty well. I am not going to delete that mechanism just for the sake of promoting standards, because then it's gonna take ages for the ecosystem to catch up. And from the iOS perspective that is only one line to find xcodeproj, so it's not even an issue. I can't see any benefits of doing so at this stage.

**Comment by grabbou** [comment]
We can of course automatically detect packages that do not follow standard and need to be analysed in the future. Then, we could automatically make an issue in their repo asking to adjust to the overall convention.

**Comment by Kureev** [comment]
@grabbou I like this approach ^

**Comment by grabbou** [comment]
This will be postLink hook.

**Comment by Kureev** [comment]
Seems it's not required
