### ISSUE TITLE
rnpm logo

### ISSUE THREAD

**Issue by Kureev** [rnpm/rnpm#65]
Hey folks!

I think it would be nice if we'll have a nice logo for `rnpm`. But I'm not a designer and we have no money to pay for a professional logo designer service :cry:. That's why I want to organize a small contest for designers (if we have any here). 

**What's required?**
Make a nice `rnpm` logo and post it here not later than 10th of January.

**What gets the winner?**
The winner will be mentioned in the README, LICENSE (as an author of the logo). Also, we'll send him/her a few laptop stickers with a new logo :wink: + tons of respect from me and @grabbou.

**Comment by Kureev** [comment]
Few sketches from my friend:
![](http://s17.postimg.org/40ktoz8bj/image.jpg)
![](http://s17.postimg.org/ify5a4vz3/image.jpg)
![](http://s17.postimg.org/dvbyv7c9r/image.jpg)

**Comment by sonnylazuardi** [comment]
![logornpm-vertical](https://cloud.githubusercontent.com/assets/856609/12014053/18eb416a-ad57-11e5-85df-6e65ea590fb8.png)
![logornpm-trans](https://cloud.githubusercontent.com/assets/856609/12014054/18ee89f6-ad57-11e5-8dff-15aa44b566a2.png)
![logornpm](https://cloud.githubusercontent.com/assets/856609/12014055/193022d0-ad57-11e5-82c0-120caf64db70.png)

**Comment by WellDone2094** [comment]
a box with react icon on it

**Comment by michelemazzucco** [comment]
Here's a quick mockup, just for fun :)

![screen shot 2015-12-28 at 22 10 44](https://cloud.githubusercontent.com/assets/4552203/12025502/dcb56596-adaf-11e5-94d0-3dcc2631cd78.png)

**Comment by grabbou** [comment]
That's awesome!! All of these are stunning, but I am in love with @michelemazzucco first one! <3

**Comment by Kureev** [comment]
I like all of them, but lets wait for 10th of Jan to start an official polling 😉

**Comment by margheimd** [comment]
My brother recommended I give this a shot for you guys. As an aspiring graphic designer, I'm trying to get my name out there and some work in my portfolio.
![rnmp-logo](https://cloud.githubusercontent.com/assets/16293229/12042720/3e72eab8-ae43-11e5-8b44-9cb2bcaedac8.png)

**Comment by michelemazzucco** [comment]
Thank you so much @grabbou!

**Comment by okonet** [comment]
A quick concept:

<img width="336" alt="2015-12-30 at 20 41" src="https://cloud.githubusercontent.com/assets/11071/12056350/d0da8fee-af35-11e5-8c7d-381200906db2.png">

**Comment by sonnylazuardi** [comment]
@michelemazzucco your logo is very cool :+1:

**Comment by Kureev** [comment]
Dear community, thanks for your efforts! Now it's time to vote! 

[Check a new issue for polling!](https://github.com/rnpm/rnpm/issues/68)
