### ISSUE TITLE
End-user config prompt for rnpm

### ISSUE THREAD

**Issue by cbrevik** [rnpm/rnpm#67]
Hi guys! As per our discussion on Discord, here are some mad ramblings;

For my specific case, I need the end-user to input a Google Analytics tracking id if they want to use my [Google Analytics bridge](https://github.com/idehub/react-native-google-analytics-bridge).

This tracking id is unique for each end-user, and in some cases unique for each platform (Android / iOS). 

Even though rnpm can do most of the heavy lifting when linking my module, there are still [some manual steps that need to be done](https://github.com/idehub/react-native-google-analytics-bridge#installation-with-rnpm). The tracking id needs to be consumable from native code, which is why I ask my end-user to manually put it into Info.plist (iOS) and their java code (Android).

Ideally, I'd like rnpm to be able to prompt the user for such values. That is to say, when they run `rnpm link react-native-google-analytics-bridge`, the tool will;

1. Ask them for their iOS GA tracking id.
2. Ask them for their Android GA tracking id.
3. Write these values into Info.plist for iOS, and some Android config file (not too familiar with Android).

Maybe this is something I could config in my package.json? Maybe not as verbose, but you know;
```
rnpm: {
    config: {
        android: [
            { 
                description: "Please input your Android GA tracking id", 
                configName: "GATrackingId" 
            }
        ],
        ios: [
            { 
                description: "Please input your iOS GA tracking id", 
                configName: "GATrackingId" 
            }
        ]
    }
}
```

Also; I know as my module changes, I will expose more config parameters. So allowing end-users to re-run config through `rnpm config react-native-google-analytics-bridge` again after updating my module would be nice. 

Similar scenarios and use cases probably exists for other native module authors, like people wrapping native modules around APIs that need some specific API key.

What do you guys think?

**Comment by grabbou** [comment]
Quick note before I get back from holidays: as per linked module -> we are going to integrate native dependency management soon this month so this will get automatically resolved, but yeah - generally prompts are lovely for better experience (especially when we assume some defaults - when something's wrong - we can just ask for it instead of quitting with log.warn/log.err)

**Comment by Kureev** [comment]
I think this one can be solved by using hooks
