### ISSUE TITLE
rnpm logo [polling]

### ISSUE THREAD

**Issue by Kureev** [rnpm/rnpm#68]
Hey everybody! I'm pretty glad to announce that we have a few options for the logo! Please, select a one you prefer and post it here. Next Sunday (17th of January) we'll announce a winner :8ball:!

[List of proposed works can be found here!](https://github.com/rnpm/rnpm/issues/65)
Good luck to everybody!

**Comment by jacob-israel-turner** [comment]
I like [this](https://cloud.githubusercontent.com/assets/856609/12060022/f8df2834-af98-11e5-8dcb-b3c9b538b41f.png) one. :+1:

**Comment by fibric** [comment]
I like the top one in https://github.com/rnpm/rnpm/issues/65#issuecomment-167658145 :+1:

**Comment by Arkni** [comment]
The top one in [#65 (comment)](https://github.com/rnpm/rnpm/issues/65#issuecomment-167482237) :+1:

**Comment by ptmt** [comment]
[+1](https://cloud.githubusercontent.com/assets/856609/12060022/f8df2834-af98-11e5-8dcb-b3c9b538b41f.png)

**Comment by agrishun** [comment]
[+1] (https://github.com/rnpm/rnpm/issues/65#issuecomment-167482237)

**Comment by grabbou** [comment]
This one https://github.com/rnpm/rnpm/issues/65#issuecomment-167658145

**Comment by cbrevik** [comment]
[Top one](https://cloud.githubusercontent.com/assets/4552203/12025502/dcb56596-adaf-11e5-94d0-3dcc2631cd78.png).

**Comment by Kureev** [comment]
I like [this one](https://cloud.githubusercontent.com/assets/856609/12060022/f8df2834-af98-11e5-8dcb-b3c9b538b41f.png)

**Comment by brentvatne** [comment]
The second one here https://github.com/rnpm/rnpm/issues/65#issuecomment-167658145

**Comment by kaphacius** [comment]
[+1](https://github.com/rnpm/rnpm/issues/65#issuecomment-167482237)

**Comment by webrangeriit** [comment]
[+1](https://github.com/rnpm/rnpm/issues/65#issuecomment-167482237)

**Comment by gbipplriau** [comment]
[+1](https://github.com/rnpm/rnpm/issues/65#issuecomment-167482237) top one

**Comment by lukehedger** [comment]
[+1](https://github.com/rnpm/rnpm/issues/65#issuecomment-168062494)

**Comment by grabbou** [comment]
I think @Kureev it's time to announce the winner

**Comment by Kureev** [comment]
Based on this poll, the winner is @sonnylazuardi:
![](https://cloud.githubusercontent.com/assets/856609/12060022/f8df2834-af98-11e5-8dcb-b3c9b538b41f.png)

**Comment by Kureev** [comment]
Thanks to everybody who took a part in this contest :+1:
