### ISSUE TITLE
[Meta] Remove `alpha` note

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm#73]
> This version is still in alpha as we are getting unit tests written. Feel free to submit bugs and feature requests. Always use this tool in a connection with source control to make sure all changes can be reverted.

I guess we are stable right now since there were not that many issues since we have started and that could be safely removed.

I propose to change it to something like:

> RNPM modifies your project settings and thus you should always use version control system to ensure any changes can be easily reverted if something goes wrong

**Comment by Kureev** [comment]
Make a PR

**Comment by grabbou** [comment]
Will do by the evening.
