### ISSUE TITLE
ReferenceError: packageName is not defined

### ISSUE THREAD

**Issue by danhawkes** [rnpm/rnpm#76]
When trying to `rnpm link react-native-vector-icons`:

rnpm: 1.4.0
node: v5.4.1
npm: 3.3.12
react-native-vector-icons: 1.0.4

    /Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:37
          log.info(`Android module ${packageName} is already linked`);
                                     ^

    ReferenceError: packageName is not defined
        at /Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:37:34
        at fn (/Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:746:34)
        at /Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:1213:16
        at /Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:166:37
        at /Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:706:43
        at /Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:167:37
        at Immediate._onImmediate (/Users/dan/.nvm/versions/node/v5.4.1/lib/node_modules/rnpm/node_modules/async/lib/async.js:1206:34)
        at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by grabbou** [comment]
Blah. Will hotfix in 5 minutes

**Comment by grabbou** [comment]
Try installing with `npm install -g rnpm` to get new version of link. The error should be gone!

**Comment by danhawkes** [comment]
Awesome, thanks for the fast fix.
