### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by udiedrichsen** [rnpm/rnpm#78]
Hi,

I didnt get the point about rnpm. Why do the world need rnpm ?
Some people suggest to use rnpm, but nobody seems knows why.
Most hits in google regarding my search rnpm or react-native package manager are not useful.

Could you update your readme with some more details or describe the workflow ?

**Comment by grabbou** [comment]
Hey,

To me, the docs are ok. There's rationale, installation & available commands section. As the same suggest - it's package manager and it links native dependencies.

> Some people suggest to use rnpm, but nobody seems knows why.

Would you mind quoting anyone? So far the experience has been pretty cool and I haven't heard of anyone having troubles.

The workflow is clearly described in `Available commands` as well as https://facebook.github.io/react-native/docs/linking-libraries-ios.html#automatic-linking

> "rnpm" is a community project that allows linking of native dependencies automatically:

**Comment by udiedrichsen** [comment]
Ah ok, thats the missing step: Thx !
I didn't read that facebook page.

**Comment by Kureev** [comment]
Maybe we need to be a bit more explicit what means "linking dependencies" in our README.md. At least refer to this facebook page. Wdyt, Mike?

**Comment by grabbou** [comment]
Maybe just refer to the page? Not sure if we want to explain all these things! Just 'of you are wondering what he heck is all that stuff, read ...' :gun:

**Comment by Kureev** [comment]
It's definitely a good first step!
