### ISSUE TITLE
Malformed gradle module paths

### ISSUE THREAD

**Issue by danhawkes** [rnpm/rnpm#79]
Running `rnpm link` creates the following paths in `settings.gradle`

    +project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons//Users/dan/<removed>/app/node_modules/react-native-vector-icons/android')
    +include ':react-native-camera'
    +project(':react-native-camera').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-camera//Users/dan/<removed>/node_modules/app/react-native-camera/android')
    +include ':react-native-vector-icons'

Notice the relative and absolute paths to the module seem to have been concatenated, resulting in an invalid path.

`rnpm -V 1.4.1`

**Comment by Kureev** [comment]
Sorry for this issue. I'll do my best to fix it asap

**Comment by Kureev** [comment]
Theoretically, https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/patches/makeSettingsPatch.js#L4-L7 should do the trick. Can you confirm that you're using `rnpm-plugin-link@1.5.1`?

**Comment by danhawkes** [comment]
I think it's actually `1.5.2`, or at least that's the version in `rnpm/node_modules/rnpm-plugin-link/package.json`.

**Comment by grabbou** [comment]
Hey @danhawkes, would you mind console.logging projectConfig & dependencyConfig above the lines pasted by @Kureev and sending it here? That'd be very helpful, there is definitely something weird going on.

**Comment by Kureev** [comment]
I think that should be closed now, right?

**Comment by grabbou** [comment]
I don't think so... the issue here is about two different paths that for some reason are not relative to each other. Let's wait for console.log output to double check.

**Comment by danhawkes** [comment]
Hmm, I'm not sure what's changed in the project, but suddenly I can't reproduce this issue. May have wiped node_modules, or updated react etc, but suddenly it seems to work as expected. Thanks anyway for the responses; will re-open again if I can reproduce it reliably.

**Comment by grabbou** [comment]
Good to know! Good luck on your project ;)
