### ISSUE TITLE
Add xcode linker flag to main project 

### ISSUE THREAD

**Issue by tuanpmt** [rnpm/rnpm#81]
Hello,
My react-native package have xcode library project and need to add linker flag to main project: 
`-framework CFNetwork -framework Security -licucore`
How to do it automatic with rnpm.

Thanks,

**Comment by grabbou** [comment]
Hey,

This is out of scope for rnpm.

Please check the below link:
http://docs.millennialmedia.com/ios-ad-sdk/adding-objc-linker-flag-xcode.html
<img src="http://docs.millennialmedia.com/ios-ad-sdk/adding-objc-linker-flag.png" />
