### ISSUE TITLE
It aims to work with almost all packages available with no extra configuration required.

### ISSUE THREAD

**Issue by tristangodfrey** [rnpm/rnpm#96]
Should there perhaps be a list of popular packages that do and don't work?

For example `react-native-code-push` requires an extra binary to be linked in addition to the work that `rnpm link` does.

**Comment by Kureev** [comment]
Hi Tristan,

I'm afraid this list would be too big :smiley: 
`react-native-code-push` authors can use our hook system to link an additional library (if it's needed).

**Comment by grabbou** [comment]
Well, it works with them. By `it works` we mean it finds the project and links it. Native dependencies will be supported in the future, but for now - this only applies to xcodeproject / gradle.
