### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by briancaw** [rnpm/rnpm#99]
Suggestions:

1)  NOOP commands should log something
2)  There should be a verbose option
3)  Verbose option should log info about linking

In particular, I think that the following

`rnpm info Android module react-native-appboy-sdk is already linked`

might be a bug (not sure if it's on our end our rnpm's), but I'm finding it a bit involved to track down why it thinks that.

Thanks!

**Comment by Kureev** [comment]
That message just tells you that module you're trying to link has been already linked and wouldn't be linked again :) Is it an issue? Or I misunderstood this one?

**Comment by briancaw** [comment]
Hey @Kureev,

Thanks for the quick reply.  The issue I had was that my package was formatted incorrectly and I had run  `rnpm link` a couple times such that it was having some strange behavior - e.g. some parts of the linking were already done, but `rnpm link` would do earlier steps that were undone and then output that message that seemed like it was a NOOP (I was testing on a project not in version control, so a lot of this would have been more easily visible for most folks).

So, part of it was that my environment was a bit corrupted, but in general I think that just logging more information would be very useful, especially for folks creating modules to work with rnpm or who are debugging rnpm issues.  

On a related note, do you know if there's an explicit specification somewhere for what a rnpm package must look like?  Or is it just pattern matching the react-native FB modules?

Thanks again!

**Comment by Kureev** [comment]
I think [that's what you're looking for](https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/registerNativeModule.js#L39-L42) :wink: 

I was thinking about the `doctor` plugin for rnpm, so that could be one of the use-cases. But I need to discuss it with @grabbou first of all.

**Comment by grabbou** [comment]
Yeah, that's something we've been thinking about and I think we can add more verbose logs to `link`. Also - this week I am planning to land interface questions so that you can answer some of them `as you go` and have them automatically stored in your package.json (e.g. "We couldn't find XYZ file, is it one of these?")

**Comment by grabbou** [comment]
@briancaw would you mind helping us with that by sending over a PR with few logs here and there? ;)

**Comment by Kureev** [comment]
Seems this one is outdated and not actionable. I'll re-open it if we get a new feedback from the TS
